// The words of the articles page: the column of topics and views, the list,
// and the article being read. texts.js adds them to the dashboard's own.
// Jira: DM42-80, DM42-31

export const fi = {
  'side.ask': 'Kysy artikkeleilta',
  'side.askHint': 'Tekoäly vastaa juttujen pohjalta ja kertoo, mistä jutusta mikin on.',
  'place.ask': 'Kysy artikkeleilta',
  'ask.label': 'Kysymys',
  'ask.placeholder': 'Kysy, mitä lähteissä on kirjoitettu jostakin aiheesta',
  'ask.days': 'Mistä ajasta',
  'ask.days.30': 'Viimeiset 30 päivää',
  'ask.days.90': 'Viimeiset 3 kuukautta',
  'ask.days.365': 'Viimeinen vuosi',
  'ask.days.3650': 'Koko ajalta',
  'ask.submit': 'Kysy',
  'ask.busy': 'Etsitään juttuja ja kirjoitetaan vastausta…',
  'ask.emptyTitle': 'Mitä haluat tietää?',
  'ask.intro': 'Tekoäly etsii kysymykseen sopivat jutut, enintään kahdeksan, ja vastaa vain niiden tiivistelmien pohjalta. Numero vastauksessa avaa jutun viereen, ja sieltä sen voi valita uutiskirjeeseen.',
  'ask.try': 'Esimerkkejä',
  'ask.example1': 'Mitä tekoälystä on kirjoitettu opettajille?',
  'ask.example2': 'Miten oppimisanalytiikkaa käytetään?',
  'ask.example3': 'Mitä etäopetuksesta on kerrottu?',
  'ask.memory': 'Tekoäly muistaa edellisen kysymyksen, joten voit jatkaa siitä, esimerkiksi: Entä lukioissa? Uusi keskustelu aloittaa alusta.',
  'ask.askedAs': 'Haettu muodossa: {q}',
  'ask.none': 'Kysymykseen sopivia juttuja ei löytynyt ({when}). Kokeile muita sanoja tai pidempää aikaa.',
  'ask.wider': 'Hae uudelleen: {when}',
  'ask.retry': 'Kysy uudelleen',
  'ask.meta.one': 'Vastaus 1 jutun pohjalta',
  'ask.meta.other': 'Vastaus {n} jutun pohjalta',
  'ask.check': 'Tarkista vastaus jutuista ennen kuin käytät sitä.',
  'ask.sources': 'Jutut, joista vastaus on',
  'ask.state.picked': 'Valittu: {section}',
  'ask.state.later': 'Myöhemmin',
  'ask.state.dismissed': 'Ei käytetä',
  'ask.copy': 'Kopioi vastaus',
  'ask.copied': 'Vastaus ja sen jutut kopioitu.',
  'ask.copyFailed': 'Kopiointi ei onnistunut tässä selaimessa.',
  'ask.new': 'Uusi keskustelu',
  'ask.cleared': 'Keskustelu tyhjennetty.',
  'ask.readerEmpty': 'Numero vastauksessa tai juttu sen alla avautuu tähän.',
  'ask.left': '{n} merkkiä jäljellä',
  'ask.cite': 'Avaa juttu {n}: {title}',
  'place.inbox': 'Uudet',
  'place.tag': 'Asiasana: {tag}',
  'place.none': 'Ei aihetta',
  'place.note.inbox': 'Tiivistetyt uutiset ja seurattujen aiheiden opinnäytetyöt viimeiseltä {days} päivältä. Lisää uutiskirjeeseen, säästä myöhemmäksi tai jätä pois.',
  'place.note.topic': 'Kaikki, joilla on jokin aiheen asiasanoista: {terms}.',
  'place.note.tag': 'Kaikki, joilla on YSO-asiasana {tag}.',
  'place.note.none': 'Uutiset, joita mikään aihe ei kata. Täältä näkee, puuttuuko jokin aihe.',
  'place.note.source': 'Kaikki tästä lähteestä.',
  'place.note.signal': 'Artikkelit, joista tekoäly löysi tämän aiheen, {from}–{to}. {reason}',
  'note.all': 'Kaikki kerätyt artikkelit ja opinnäytetyöt, myös ohitetut ja pois jätetyt.',
  'place.empty.inbox': 'Kaikki uudet on käyty läpi. Uudet tulevat tänne seuraavan tarkistuksen jälkeen.',
  'place.empty.topic': 'Tässä aiheessa ei ole vielä artikkeleita.',
  'place.empty.tag': 'Tällä asiasanalla ei ole artikkeleita.',
  'place.empty.none': 'Kaikilla uutisilla on aihe.',
  'place.empty.source': 'Tästä lähteestä ei ole vielä mitään.',

  'side.label': 'Aiheet ja näkymät',
  'places.label': 'Listat ja aiheet',
  'places.menu': 'Valikko',
  'places.ask': 'Kysy',
  'side.close': 'Sulje',
  'side.followed': 'Seuratut aiheet',
  'side.followedHint': 'Näiden aiheiden opinnäytetyöt tulevat Uusiin.',
  'side.other': 'Muut aiheet',
  'side.none': 'Ei aihetta',
  'side.sources': 'Lähteet',
  'side.drive': 'Yhdistyksen Drive',
  'side.driveNew': '{n} uutta',
  'side.more': 'Muut näkymät',
  'side.follow': 'Seuraa',
  'side.followLabel': 'Seuraa aihetta {topic}',
  'side.unfollow': 'Lopeta aiheen {topic} seuraaminen',
  'side.newCount': '{n} uutta',

  'target.label': 'Valinnat menevät',
  'target.new': 'Uuteen uutiskirjeeseen',
  'target.newHint': 'Ensimmäinen valinta tekee uuden luonnoksen.',
  'target.picked.one': '1 artikkeli valittu',
  'target.picked.other': '{n} artikkelia valittu',
  'target.open': 'Avaa uutiskirje',

  'search.label': 'Hae',
  'search.hint': 'Hae otsikoista, tiivistelmistä ja asiasanoista',
  'count.one': '1 artikkeli',
  'count.other': '{n} artikkelia',
  'day.today': 'Tänään',
  'day.yesterday': 'Eilen',

  'row.thesis': 'Opinnäytetyö',
  'row.publication': 'Julkaisu',
  'row.waiting': 'Odottaa tekoälyä',
  'row.skipped': 'Ohitettu',
  'row.attention': 'Vaatii huomiota',
  'row.noTags': 'ei asiasanoja',
  'row.tagsComing': 'asiasanat tulossa',
  'row.later': 'Myöhemmin',
  'row.dismissed': 'Ei käytetä',
  'row.sent': 'Lähetetty',

  'reader.position': '{place} · {n} / {total}',
  'reader.back': 'Takaisin',
  'reader.prev': 'Edellinen',
  'reader.next': 'Seuraava',
  'reader.open': 'Avaa alkuperäinen',
  'reader.topics': 'Aiheet',
  'reader.noTopic': 'Ei aihetta',
  'reader.noLearningTag': 'Ei aihetta, koska oppimisen asiasanaa ei ole',
  'reader.tags': 'Asiasanat',
  'reader.tagsComing': 'Asiasanat tulevat 15 minuutin kuluessa.',
  'reader.tagHint': 'Kaikki, joilla on asiasana {tag}',
  'reader.removeTag': 'Poista asiasana {tag}',
  'reader.addTag': 'Lisää asiasana',
  'reader.addTagHint': 'Kirjoita asiasanan alku',
  'reader.noTerms': 'YSO:sta ei löytynyt tällä alulla.',
  'reader.also': 'myös {name}',
  'reader.signal': 'Signaali: {topic}',
  'reader.signalOpen': 'Näytä signaalin {topic} artikkelit',
  'side.signals': 'Signaalit',
  'side.signalsHint': 'Aiheet, jotka toistuvat uutisissa, haettu {date}. Uusi haku tehdään joka maanantai.',
  'side.signalsNone': 'Ei vielä signaaleja. Haku tehdään joka maanantai.',
  'side.findSignals': 'Hae signaalit nyt',
  'side.signalsSingle': 'Yhdestä artikkelista ({n})',
  'side.findingSignals': 'Haku käynnistyi. Tulokset tulevat tähän muutaman minuutin kuluttua.',
  'place.signal': 'Signaali: {topic}',
  'reader.summary': 'Tekoälyn tiivistelmä',
  'reader.abstract': 'Tekijän tiivistelmä',
  'reader.licenceOpen': 'Lisenssi {licence}: tekstiä saa käyttää lisenssin ehdoin, kun tekijä ja lähde mainitaan.',
  'reader.licenceClosed': 'Kaikki oikeudet pidätetään, joten uutiskirjeeseen tulee oma tiivistelmä. Tekoäly kirjoittaa sen, kun lisäät työn uutiskirjeeseen.',
  'reader.driveSave': 'Tallenna Driveen',
  'reader.driveSaved': 'Tallennettu Driveen {date} kansioon {folder}',
  'reader.driveOpen': 'Avaa',
  'reader.driveAgain': 'Tallenna uudelleen',
  'reader.driveChanged': 'Driven asiakirja muuttui {when}. Uutiskirje, jossa artikkeli on, odottaa, että joku katsoo sen Tarkistuksessa.',
  'driveSave.title': 'Tallenna Driveen',
  'driveSave.folder': 'Kansio',
  'driveSave.newFolder': 'Uusi kansio…',
  'driveSave.newName': 'Uuden kansion nimi',
  'driveSave.where': 'Tallennetaan kansioon {path}.',
  'driveSave.doc': 'Google-dokumentti, jossa ovat otsikko, lähde, päivä, linkki, tekoälyn tiivistelmä, tapahtuman tiedot sekä aiheet ja asiasanat.',
  'driveSave.noText': 'Alkuperäisen artikkelin koko tekstiä ei tallenneta: se kuuluu julkaisijalle.',
  'driveSave.picture.own': 'Artikkelin kuva tallentuu viereen: se on yhdistyksen oma.',
  'driveSave.picture.open': 'Artikkelin kuva tallentuu viereen: sillä on avoin lisenssi, ja kuvaaja mainitaan.',
  'driveSave.picture.check': 'Artikkelin kuvaa ei tallenneta: se kuuluu julkaisijalle.',
  'driveSave.savedBefore': 'Tallennettu jo {date} kansioon {folder}. Uusi tallennus tekee uuden dokumentin.',
  'driveSave.cannot.my_drive': 'Tallennus ei onnistu: kansio on jonkun omassa Drivessa, jonne Google ei anna työkalun tallentaa. Kansion pitää olla jaetussa Drivessa.',
  'driveSave.cannot.read_only': 'Tallennus ei onnistu: työkalu saa vain lukea kansiota. Ylläpitäjä voi jakaa sille yhden alikansion muokattavaksi.',
  'driveSave.cannot.ambiguous': 'Tallennus ei ole käytössä: työkalu saa muokata useampaa alikansiota. Ylläpitäjä jättää muokkausoikeuden vain yhteen.',
  'driveSave.cannot.off': 'Drive ei ole käytössä.',
  'driveSave.save': 'Tallenna',
  'driveSave.saving': 'Tallennetaan…',
  'driveSave.done': 'Tallennettu Driveen kansioon {folder}.',
  'driveSave.openFolder': 'Avaa kansio Drivessa',
  'driveList.button': 'Tallenna lista Driveen',
  'driveList.lead': 'Listan artikkelit yhteen Google-dokumenttiin ja samat taulukkoon: otsikot, lähteet, linkit ja tiivistelmät.',
  'driveList.count': 'Tallennetaan {n} artikkelia.',
  'driveList.max': 'Listalla on {total} artikkelia, joista tallennetaan 100 ensimmäistä.',
  'driveList.done': 'Lista tallennettu Driveen kansioon {folder}: {n} artikkelia.',
  'drivePlace.files': 'Näytä kansion tiedostot',
  'live.above.one': '1 uusi artikkeli ylempänä',
  'live.above.other': '{n} uutta artikkelia ylempänä',
  'live.arrived.one': '1 uusi artikkeli tuli listaan.',
  'live.arrived.other': '{n} uutta artikkelia tuli listaan.',
  'live.gone': 'Artikkeli ei ole enää työkalussa.',
  'reader.summaryComing': 'Tekoäly kirjoittaa tiivistelmän 15 minuutin kuluessa.',
  'reader.summariseNow': 'Tiivistä nyt',
  'reader.addTo': 'Lisää uutiskirjeeseen ”{issue}”',
  'reader.addToNew': 'Lisää uutiskirjeeseen',
  'reader.how': 'Paina osiota, johon artikkeli tulee. Seuraava artikkeli avautuu sen jälkeen.',
  'reader.howNew': 'Paina osiota, johon artikkeli tulee. Ensimmäinen valinta tekee uuden uutiskirjeen.',
  'reader.howMove': 'Siirrä se toiseen osioon painamalla sitä, tai peru päätös.',
  'reader.sectionWhat.own_news': 'Yhdistyksen uutiset ja hankkeet',
  'reader.sectionWhat.events': 'Tilaisuudet ja koulutukset',
  'reader.sectionWhat.member_news': 'Jäsenten kuulumiset',
  'reader.sectionWhat.highlights': 'Uutisia ja tutkimusta alalta',
  'reader.sectionWhat.training': 'Koulutukset ja kurssit',
  'reader.suggested': 'Ehdotus',
  'reader.why.chosen': 'Valittu lähetettäessä',
  'reader.why.drive_folder': 'Drive-kansiosta {name}',
  'reader.why.event': 'Tapahtuma {date}',
  'reader.why.deadline': 'Ilmoittautuminen {date} mennessä',
  'reader.why.invitation': 'Kutsu tapahtumaan',
  'reader.why.member_post': 'Yhdistyksen jäsenkuulumisista',
  'reader.why.own_site': 'Yhdistyksen omalta sivulta',
  'reader.why.member_site': 'Jäseneltä: {name}',
  'reader.why.association_named': 'Mainitsee yhdistyksen',
  'reader.why.member_named': 'Mainitsee jäsenen: {name}',
  'reader.why.source_section': 'Toimittajien valinta tälle lähteelle',
  'reader.why.learning_factory': 'Learning Factoryn sivulta',
  'reader.pictureCredit': 'Kuva: {credit}',
  'reader.pictureRights.own': 'yhdistyksen oma kuva',
  'reader.pictureRights.open': 'avoin lisenssi, lähde mainitaan',
  'reader.pictureRights.check': 'uutiskirjeessä vain luvalla',
  'reader.chosen': 'Valittu',
  'reader.notForIt': 'Ei tähän kirjeeseen?',
  'reader.later': 'Säästä myöhemmäksi',
  'reader.laterShort': 'Myöhemmin',
  'reader.laterHint': 'Siirtyy Myöhemmin-listaan, josta sen voi lisätä myöhempään kirjeeseen.',
  'reader.dismiss': 'Ei käytetä',
  'reader.dismissHint': 'Siirtyy Ei käytetä -listaan, eikä näy enää Uusissa.',
  'reader.clear': 'Peru päätös',
  'reader.decidedBy': '{name}, {when}',
  'reader.sentIn': 'Lähetetty uutiskirjeessä {issue}.',
  'reader.keysPrev': 'edellinen',
  'reader.keysNext': 'seuraava',
  'reader.keysLater': 'myöhemmin',
  'reader.keysDismiss': 'ei käytetä',

  'toast.picked': 'Lisätty osioon {section}.',
  'toast.pickedThesis': 'Lisätty osioon {section}. Tekoäly kirjoittaa tiivistelmän 15 minuutin kuluessa.',
  'toast.later': 'Säästetty myöhemmäksi.',
  'toast.dismissed': 'Jätetty pois.',
  'toast.cleared': 'Päätös peruttu.',
  'toast.undo': 'Peru',
  'toast.followed': 'Seuraat aihetta {topic}. Sen opinnäytetyöt tulevat Uusiin.',
  'toast.unfollowed': 'Et enää seuraa aihetta {topic}.',
  'toast.tagAdded': 'Lisätty asiasana {tag}.',
  'toast.tagRemoved': 'Poistettu asiasana {tag}.',
  'toast.sourceSection': 'Lähteen ”{source}” artikkeleille ehdotetaan nyt osiota {section}.',
  'toast.sourceSectionStopped': 'Lähteen ”{source}” artikkeleille ei enää ehdoteta omaa osiota.',
  'toast.sourceSectionKept': 'Ehdotus pysyy ennallaan.',
  'offer.label': 'Osioehdotus',
  'offer.set': 'Lähteen ”{source}” kolme viimeistä artikkelia on valittu osioon {section}, vaikka ehdotus oli {suggested}.',
  'offer.setOther': 'Lähteen ”{source}” kolme viimeistä artikkelia on valittu osioon {section}, vaikka ehdotus oli toinen.',
  'offer.setAsk': 'Ehdotetaanko sen artikkeleille jatkossa osiota {section}?',
  'offer.setNote': 'Tapahtuma, jolla on päivämäärä, ehdotetaan silti Tapahtumiin.',
  'offer.setYes': 'Ehdota jatkossa',
  'offer.setNo': 'Ei',
  'offer.stop': 'Lähteen ”{source}” artikkeleille ehdotetaan osiota {section}, mutta kolme viimeistä on valittu muualle.',
  'offer.stopAsk': 'Lopetetaanko tämä ehdotus?',
  'offer.stopYes': 'Lopeta ehdotus',
  'offer.stopNo': 'Pidä',

  'error.no_such_topic': 'Tällä numerolla ei ole aihetta.',
  'error.no_such_tag': 'Artikkelilla ei ole tätä asiasanaa.',
  'error.not_a_term': 'YSO:ssa ei ole tällaista asiasanaa.',
  'error.finto_unreachable': 'Finto, josta asiasanat tulevat, ei vastannut. Yritä hetken päästä uudelleen.',
  'side.unseen': '{n} lukematonta',
  'side.editTopics': 'Muokkaa aiheita',

  'place.topics': 'Aiheet',
  'place.note.topics': 'Aihe on lista YSO-asiasanoja. Artikkeli kuuluu aiheeseen, jos sillä on jokin aiheen asiasanoista, ja seuratun aiheen opinnäytetyöt tulevat Uusiin.',

  'topic.new': 'Uusi aihe',
  'topic.newName': 'Uuden aiheen nimi',
  'topic.create': 'Luo',
  'topic.cancel': 'Peru',
  'topic.rowNew': '{n} uutta',
  'topic.rowTerms.one': '1 asiasana',
  'topic.rowTerms.other': '{n} asiasanaa',
  'topic.rowFollowed': 'seurattu',
  'topic.name': 'Aiheen nimi',
  'topic.saved': 'Tallennettu',
  'topic.follow': 'Seuraa, jolloin aiheen opinnäytetyöt tulevat Uusiin',
  'topic.terms': 'Asiasanat',
  'topic.noTerms': 'Aiheella ei ole vielä asiasanoja. Lisää ensimmäinen hakemalla YSO:sta.',
  'topic.addTerm': 'Lisää asiasana',
  'topic.removeTerm': 'Poista asiasana {term} aiheesta',
  'topic.termHint': 'Kaikki, joilla on asiasana {term}',
  'topic.news': 'uutista viimeisten {days} päivän ajalta',
  'topic.theses': 'opinnäytetyötä viime viikolta, joissa on myös oppimisen asiasana',
  'topic.thesesAll': 'opinnäytetyötä viime viikolta ilman tätä ehtoa',
  'topic.thesesTitle': 'Opinnäytetyöt, jotka tulivat aiheeseen viime viikolla',
  'topic.thesesNone': 'Viime viikolla ei tullut yhtään.',
  'topic.showDropped': 'Näytä myös ehdon pois jättämät ({n})',
  'topic.hideDropped': 'Piilota ehdon pois jättämät',
  'topic.dropped': 'Ei oppimisen asiasanaa',
  'topic.open': 'Näytä aiheen artikkelit',
  'topic.delete': 'Poista aihe',
  'topic.deleteConfirm': 'Poistetaanko aihe {name}? Artikkelit ja niiden asiasanat säilyvät.',
  'topic.deleted': 'Aihe {name} poistettu.',
  'topic.created': 'Aihe {name} luotu. Lisää sille asiasanat.',
  'topic.termAdded': 'Lisätty asiasana {term}.',
  'topic.termRemoved': 'Poistettu asiasana {term}.',
  'topic.none': 'Aiheita ei ole. Luo ensimmäinen.',
  'topic.pick': 'Valitse aihe listasta.',

  'reader.originalTitle': 'Alkuperäinen otsikko',
  'reader.titleByAi': 'Suomennos on tekoälyn.',
  'event.when': 'Milloin',
  'event.where': 'Missä',
  'event.deadline': 'Määräaika',
  'event.line': 'Uutiskirjeeseen',
  'event.byAi': 'Tekoäly poimi nämä artikkelista. Tarkista ennen käyttöä.',
  'event.label': 'Tapahtuma',
  'event.deadlineOn': 'Määräaika {date}',
  'event.byAiShort': 'tekoälyn poimimat, tarkista ennen käyttöä',
  'reader.aside': 'Artikkelin aiheet ja tiedot',
  'reader.suggestion': 'Ehdotus: {section}',
  'reader.suggestionWhy': 'Ehdotus: {section} ({why})',

  'error.topic_name_taken': 'Samanniminen aihe on jo olemassa.',
  'error.no_such_term': 'Aiheella ei ole tätä asiasanaa.',
  'side.calendar': 'Tapahtumakalenteri',
  'places.calendar': 'Kalenteri',
  'place.events': 'Tapahtumakalenteri',
  'place.note.events': 'Päivät ja määräajat, jotka tekoäly poimi artikkeleista. Tarkista ennen käyttöä.',
  'cal.count.one': '1 tapahtuma tai määräaika tässä kuussa',
  'cal.count.other': '{n} tapahtumaa ja määräaikaa tässä kuussa',
  'cal.prev': 'Edellinen kuukausi',
  'cal.next': 'Seuraava kuukausi',
  'cal.thisMonth': 'Tämä kuukausi',
  'cal.caption': 'Tapahtumat ja määräajat, {month}',
  'cal.more.one': '+1 muu',
  'cal.more.other': '+{n} muuta',
  'cal.moreLabel': 'Kaikki päivän {day} tapahtumat listassa',
  'cal.send': 'Uutiskirje ”{name}” lähtee',
  'cal.deadline': 'Ilmoittautuminen päättyy',
  'cal.label.event': 'Tapahtuma {day}: {title}',
  'cal.label.deadline': 'Ilmoittautuminen päättyy {day}: {title}',
  'cal.legend.event': 'Tapahtuma',
  'cal.legend.deadline': 'Ilmoittautumisen viimeinen päivä',
  'cal.legend.picked': 'Valittu uutiskirjeeseen',
  'cal.legend.send': 'Uutiskirjeen lähtöpäivä',
  'cal.emptyTitle': 'Tässä kuussa ei ole tapahtumia',
  'cal.empty': 'Tapahtumia tulee, kun lähteet tuovat juttuja, joissa on päivämäärä. Tapahtumajärjestäjien sivustoja voi lisätä lähteiksi.',
  'cal.nextMonth': 'Seuraava kuukausi',
  'row.event': 'Tapahtuma {date}',
  'row.eventNow': 'käynnissä',
  'row.signUp': 'ilmoittautuminen {date} asti',
  'row.signUpOver': 'ilmoittautuminen päättyi {date}',
  'row.deadlineOnly': 'Määräaika {date}',
  'row.beforeSend': 'ennen lähtöä',
  'row.byAi': 'Tekoälyn poimima:',
  'event.beforeSend': 'Tapahtuu ennen kuin uutiskirje lähtee {date}.',
  'event.deadlineBeforeSend': 'Ilmoittautuminen päättyy ennen kuin uutiskirje lähtee {date}.',
  'place.suggested': 'Ehdotettu: {section}',
  'place.note.suggested': 'Uudet, joille ehdotetaan osiota {section}. Lisää ne uutiskirjeeseen, säästä myöhemmäksi tai jätä pois.',
  'place.empty.suggested': 'Tälle osiolle ei ole nyt ehdotuksia Uusissa.',
  'ask.add': 'Lisää',
  'ask.addLabel': 'Lisää juttu ”{title}” uutiskirjeeseen',
  'ask.pickedLabel': 'Juttu ”{title}” on osiossa {section}. Siirrä tai poista',
  'ask.menuTitle': 'Lisää uutiskirjeeseen',
  'ask.menuSection': 'Osio',
  'ask.suggestedOption': '{section} (ehdotus)',
  'ask.removePick': 'Poista uutiskirjeestä',
  'ask.sentPick': 'Lähetetty',
  'ask.next': 'Jatka kysymällä',
  'ask.recent': 'Viimeksi kysytyt',
  'ask.forget': 'Unohda kysymys ”{q}”',
  'ask.forgotten': 'Kysymys unohdettu.',
  'ask.readerTitle': 'Avaa juttu vastauksesta',
  'reader.emptyTitle': 'Valitse juttu listasta',
  'reader.emptyHint': 'Avaa juttu napsauttamalla. J ja K vievät edelliseen ja seuraavaan.',
  'results.noneTitle': 'Ei osumia',
  'place.emptyTitle.inbox': 'Kaikki käyty läpi',
  'place.emptyTitle': 'Täällä ei ole mitään',
  'topic.noneTitle': 'Ei vielä aiheita',
  'topic.pickTitle': 'Valitse aihe',
  'side.editSources': 'Muokkaa lähteitä',
  'target.planned': 'Lähtee {day}, {when}',
  'target.fill': 'Valitut osioittain',
  'status.openSources': 'Avaa lähteet',
};

export const en = {
  'side.ask': 'Ask the articles',
  'side.askHint': 'The AI answers from the articles and says which one each thing is from.',
  'place.ask': 'Ask the articles',
  'ask.label': 'Question',
  'ask.placeholder': 'Ask, in Finnish, what the sources have written about something',
  'ask.days': 'From',
  'ask.days.30': 'The last 30 days',
  'ask.days.90': 'The last 3 months',
  'ask.days.365': 'The last year',
  'ask.days.3650': 'All time',
  'ask.submit': 'Ask',
  'ask.busy': 'Finding articles and writing the answer…',
  'ask.emptyTitle': 'What would you like to know?',
  'ask.intro': 'The AI finds the articles that fit the question, at most eight, and answers from their summaries only. A number in the answer opens the article beside it, where it can be picked for the newsletter.',
  'ask.try': 'Examples',
  'ask.example1': 'Mitä tekoälystä on kirjoitettu opettajille?',
  'ask.example2': 'Miten oppimisanalytiikkaa käytetään?',
  'ask.example3': 'Mitä etäopetuksesta on kerrottu?',
  'ask.memory': 'The AI remembers the previous question, so you can follow on from it, for example: Entä lukioissa? A new conversation starts afresh.',
  'ask.askedAs': 'Searched as: {q}',
  'ask.none': 'No articles fitted the question ({when}). Try other words or a longer time.',
  'ask.wider': 'Search again: {when}',
  'ask.retry': 'Ask again',
  'ask.meta.one': 'Answered from 1 article',
  'ask.meta.other': 'Answered from {n} articles',
  'ask.check': 'Check the answer against the articles before you use it.',
  'ask.sources': 'The articles the answer is from',
  'ask.state.picked': 'Picked: {section}',
  'ask.state.later': 'Later',
  'ask.state.dismissed': 'Not used',
  'ask.copy': 'Copy the answer',
  'ask.copied': 'The answer and its articles were copied.',
  'ask.copyFailed': "Copying didn't work in this browser.",
  'ask.new': 'New conversation',
  'ask.cleared': 'The conversation was cleared.',
  'ask.readerEmpty': 'A number in an answer, or an article under it, opens here.',
  'ask.left': '{n} characters left',
  'ask.cite': 'Open article {n}: {title}',
  'place.inbox': 'New',
  'place.tag': 'Tag: {tag}',
  'place.none': 'No topic',
  'place.note.inbox': 'Summarised news and the theses of followed topics from the last {days} days. Add to the newsletter, keep for later or leave out.',
  'place.note.topic': 'Everything with one of the topic’s terms: {terms}.',
  'place.note.tag': 'Everything with the YSO term {tag}.',
  'place.note.none': 'News no topic covers. This shows whether a topic is missing.',
  'place.note.source': 'Everything from this source.',
  'place.note.signal': 'The articles the AI found this topic in, {from}–{to}. {reason}',
  'note.all': 'Every article and thesis collected, skipped and left-out ones too.',
  'place.empty.inbox': 'You have been through everything new. New articles come here after the next check.',
  'place.empty.topic': 'There are no articles in this topic yet.',
  'place.empty.tag': 'No articles have this tag.',
  'place.empty.none': 'Every news article has a topic.',
  'place.empty.source': 'Nothing from this source yet.',

  'side.label': 'Topics and views',
  'places.label': 'Lists and topics',
  'places.menu': 'Menu',
  'places.ask': 'Ask',
  'side.close': 'Close',
  'side.followed': 'Followed topics',
  'side.followedHint': 'Theses in these topics come to New.',
  'side.other': 'Other topics',
  'side.none': 'No topic',
  'side.sources': 'Sources',
  'side.drive': 'The association’s Drive',
  'side.driveNew': '{n} new',
  'side.more': 'Other views',
  'side.follow': 'Follow',
  'side.followLabel': 'Follow the topic {topic}',
  'side.unfollow': 'Stop following {topic}',
  'side.newCount': '{n} new',

  'target.label': 'Picks go into',
  'target.new': 'A new newsletter',
  'target.newHint': 'The first pick starts a new draft.',
  'target.picked.one': '1 article picked',
  'target.picked.other': '{n} articles picked',
  'target.open': 'Open the newsletter',

  'search.label': 'Search',
  'search.hint': 'Search titles, summaries and tags',
  'count.one': '1 article',
  'count.other': '{n} articles',
  'day.today': 'Today',
  'day.yesterday': 'Yesterday',

  'row.thesis': 'Thesis',
  'row.publication': 'Publication',
  'row.waiting': 'Waiting for the AI',
  'row.skipped': 'Skipped',
  'row.attention': 'Needs attention',
  'row.noTags': 'no tags',
  'row.tagsComing': 'tags coming',
  'row.later': 'Later',
  'row.dismissed': 'Not used',
  'row.sent': 'Sent',

  'reader.position': '{place} · {n} / {total}',
  'reader.back': 'Back',
  'reader.prev': 'Previous',
  'reader.next': 'Next',
  'reader.open': 'Open the original',
  'reader.topics': 'Topics',
  'reader.noTopic': 'No topic',
  'reader.noLearningTag': 'No topic, because it has no learning tag',
  'reader.tags': 'Tags',
  'reader.tagsComing': 'Tags come within 15 minutes.',
  'reader.tagHint': 'Everything tagged {tag}',
  'reader.removeTag': 'Remove the tag {tag}',
  'reader.addTag': 'Add a tag',
  'reader.addTagHint': 'Type the start of a term',
  'reader.noTerms': 'Nothing in YSO starts like that.',
  'reader.also': 'also {name}',
  'reader.signal': 'Signal: {topic}',
  'reader.signalOpen': 'Show the articles of the signal {topic}',
  'side.signals': 'Signals',
  'side.signalsHint': 'Topics that keep coming up in the news, found {date}. A new search runs every Monday.',
  'side.signalsNone': 'No signals yet. A search runs every Monday.',
  'side.findSignals': 'Look for signals now',
  'side.signalsSingle': 'From one article ({n})',
  'side.findingSignals': 'Looking. The results show here in a few minutes.',
  'place.signal': 'Signal: {topic}',
  'reader.summary': 'AI summary',
  'reader.abstract': 'The author’s abstract',
  'reader.licenceOpen': 'Licence {licence}: the text may be used on the licence’s terms, naming the author and the source.',
  'reader.licenceClosed': 'All rights reserved, so the newsletter gets a summary of its own. The AI writes it when you add the thesis to a newsletter.',
  'reader.driveSave': 'Save to Drive',
  'reader.driveSaved': 'Saved to Drive {date} in the folder {folder}',
  'reader.driveOpen': 'Open',
  'reader.driveAgain': 'Save again',
  'reader.driveChanged': 'The Drive document changed {when}. The newsletter the article is in waits for someone to look at it in Check.',
  'driveSave.title': 'Save to Drive',
  'driveSave.folder': 'Folder',
  'driveSave.newFolder': 'New folder…',
  'driveSave.newName': 'The new folder’s name',
  'driveSave.where': 'Saved in the folder {path}.',
  'driveSave.doc': 'A Google Doc with the title, source, date, link, the AI’s summary, the event’s details, and the topics and tags.',
  'driveSave.noText': 'The original article’s full text is not saved: it belongs to its publisher.',
  'driveSave.picture.own': 'The article’s picture is saved beside it: it is the association’s own.',
  'driveSave.picture.open': 'The article’s picture is saved beside it: it has an open licence, and its photographer is named.',
  'driveSave.picture.check': 'The article’s picture is not saved: it belongs to its publisher.',
  'driveSave.savedBefore': 'Saved already {date} in the folder {folder}. Saving again makes a new document.',
  'driveSave.cannot.my_drive': 'Saving is not possible: the folder is in someone’s My Drive, where Google does not let the tool save. The folder has to be on a shared drive.',
  'driveSave.cannot.read_only': 'Saving is not possible: the tool may only read the folder. An admin can share one folder inside it for the tool to edit.',
  'driveSave.cannot.ambiguous': 'Saving is not in use: the tool may edit several folders. An admin leaves editing to one.',
  'driveSave.cannot.off': 'Drive is not in use.',
  'driveSave.save': 'Save',
  'driveSave.saving': 'Saving…',
  'driveSave.done': 'Saved to Drive in the folder {folder}.',
  'driveSave.openFolder': 'Open the folder in Drive',
  'driveList.button': 'Save the list to Drive',
  'driveList.lead': 'The list’s articles in one Google Doc, and the same as a sheet: titles, sources, links and summaries.',
  'driveList.count': '{n} articles are saved.',
  'driveList.max': 'The list has {total} articles; the first 100 are saved.',
  'driveList.done': 'List saved to Drive in the folder {folder}: {n} articles.',
  'drivePlace.files': 'Show the folder’s files',
  'live.above.one': '1 new article above',
  'live.above.other': '{n} new articles above',
  'live.arrived.one': '1 new article came into the list.',
  'live.arrived.other': '{n} new articles came into the list.',
  'live.gone': 'The article is no longer in the tool.',
  'reader.summaryComing': 'The AI writes the summary within 15 minutes.',
  'reader.summariseNow': 'Summarise now',
  'reader.addTo': 'Add to the newsletter “{issue}”',
  'reader.addToNew': 'Add to the newsletter',
  'reader.how': 'Press the section it goes in. The next article opens after that.',
  'reader.howNew': 'Press the section it goes in. The first pick starts a new newsletter.',
  'reader.howMove': 'Press another section to move it, or take it back.',
  'reader.sectionWhat.own_news': "The association's news and projects",
  'reader.sectionWhat.events': 'Events and trainings',
  'reader.sectionWhat.member_news': 'What the members are up to',
  'reader.sectionWhat.highlights': 'News and research from the field',
  'reader.sectionWhat.training': 'Trainings and courses',
  'reader.suggested': 'Suggested',
  'reader.why.chosen': 'Chosen when it was sent',
  'reader.why.drive_folder': 'From the Drive folder {name}',
  'reader.why.event': 'Event on {date}',
  'reader.why.deadline': 'Sign up by {date}',
  'reader.why.invitation': 'An invitation to an event',
  'reader.why.member_post': "From the association's member news",
  'reader.why.own_site': "From the association's own site",
  'reader.why.member_site': 'From a member: {name}',
  'reader.why.association_named': 'Names the association',
  'reader.why.member_named': 'Names a member: {name}',
  'reader.why.source_section': "The editors' choice for this source",
  'reader.why.learning_factory': "From Learning Factory's site",
  'reader.pictureCredit': 'Picture: {credit}',
  'reader.pictureRights.own': "the association's own picture",
  'reader.pictureRights.open': 'open licence, credited',
  'reader.pictureRights.check': 'in the newsletter only with permission',
  'reader.chosen': 'Chosen',
  'reader.notForIt': 'Not for this newsletter?',
  'reader.later': 'Save for later',
  'reader.laterShort': 'Later',
  'reader.laterHint': 'Moves to the Later list, to add to a later newsletter.',
  'reader.dismiss': 'Not used',
  'reader.dismissHint': 'Moves to the Not used list and leaves New.',
  'reader.clear': 'Take back',
  'reader.decidedBy': '{name}, {when}',
  'reader.sentIn': 'Sent in the newsletter {issue}.',
  'reader.keysPrev': 'previous',
  'reader.keysNext': 'next',
  'reader.keysLater': 'later',
  'reader.keysDismiss': 'not used',

  'toast.picked': 'Added to {section}.',
  'toast.pickedThesis': 'Added to {section}. The AI writes the summary within 15 minutes.',
  'toast.later': 'Kept for later.',
  'toast.dismissed': 'Left out.',
  'toast.cleared': 'Decision taken back.',
  'toast.undo': 'Undo',
  'toast.followed': 'You follow {topic}. Its theses come to New.',
  'toast.unfollowed': 'You no longer follow {topic}.',
  'toast.tagAdded': 'Added the tag {tag}.',
  'toast.tagRemoved': 'Removed the tag {tag}.',
  'toast.sourceSection': '{section} is now suggested for articles from “{source}”.',
  'toast.sourceSectionStopped': 'No section of its own is suggested for “{source}” any more.',
  'toast.sourceSectionKept': 'The suggestion stays as it is.',
  'offer.label': 'Section suggestion',
  'offer.set': 'The last three articles from “{source}” went into {section}, though {suggested} was suggested.',
  'offer.setOther': 'The last three articles from “{source}” went into {section}, though another section was suggested.',
  'offer.setAsk': 'Suggest {section} for its articles from now on?',
  'offer.setNote': 'An event with a date is still suggested for Events.',
  'offer.setYes': 'Suggest from now on',
  'offer.setNo': 'No',
  'offer.stop': '{section} is suggested for articles from “{source}”, but the last three went elsewhere.',
  'offer.stopAsk': 'Stop suggesting it?',
  'offer.stopYes': 'Stop suggesting',
  'offer.stopNo': 'Keep it',

  'error.no_such_topic': 'There is no topic with that number.',
  'error.no_such_tag': 'The article has no such tag.',
  'error.not_a_term': 'YSO has no such term.',
  'error.finto_unreachable': 'Finto, where the tags come from, did not answer. Try again in a moment.',
  'side.unseen': '{n} unread',
  'side.editTopics': 'Edit topics',

  'place.topics': 'Topics',
  'place.note.topics': 'A topic is a list of YSO terms. An article is in a topic when it has one of its terms, and the theses of a followed topic come to New.',

  'topic.new': 'New topic',
  'topic.newName': 'The new topic’s name',
  'topic.create': 'Create',
  'topic.cancel': 'Cancel',
  'topic.rowNew': '{n} new',
  'topic.rowTerms.one': '1 term',
  'topic.rowTerms.other': '{n} terms',
  'topic.rowFollowed': 'followed',
  'topic.name': 'Topic name',
  'topic.saved': 'Saved',
  'topic.follow': 'Follow, so the topic’s theses come to New',
  'topic.terms': 'Terms',
  'topic.noTerms': 'The topic has no terms yet. Add the first by searching YSO.',
  'topic.addTerm': 'Add a term',
  'topic.removeTerm': 'Remove the term {term} from the topic',
  'topic.termHint': 'Everything tagged {term}',
  'topic.news': 'news from the last {days} days',
  'topic.theses': 'theses from last week that also have a learning tag',
  'topic.thesesAll': 'theses from last week without that rule',
  'topic.thesesTitle': 'Theses that came to the topic last week',
  'topic.thesesNone': 'None came last week.',
  'topic.showDropped': 'Show the ones the rule left out too ({n})',
  'topic.hideDropped': 'Hide the ones the rule left out',
  'topic.dropped': 'No learning tag',
  'topic.open': 'Show the topic’s articles',
  'topic.delete': 'Delete the topic',
  'topic.deleteConfirm': 'Delete the topic {name}? The articles and their tags stay.',
  'topic.deleted': 'Deleted the topic {name}.',
  'topic.created': 'Created the topic {name}. Now give it its terms.',
  'topic.termAdded': 'Added the term {term}.',
  'topic.termRemoved': 'Removed the term {term}.',
  'topic.none': 'There are no topics. Create the first.',
  'topic.pick': 'Choose a topic from the list.',

  'reader.originalTitle': 'Original title',
  'reader.titleByAi': 'Translated by the AI.',
  'event.when': 'When',
  'event.where': 'Where',
  'event.deadline': 'Deadline',
  'event.line': 'In the newsletter',
  'event.byAi': 'The AI picked these out of the article. Check them before use.',
  'event.label': 'Event',
  'event.deadlineOn': 'Deadline {date}',
  'event.byAiShort': 'picked out by the AI, check before use',
  'reader.aside': 'The article’s topics and details',
  'reader.suggestion': 'Suggested: {section}',
  'reader.suggestionWhy': 'Suggested: {section} ({why})',

  'error.topic_name_taken': 'There is a topic with that name already.',
  'error.no_such_term': 'The topic has no such term.',
  'side.calendar': 'Events calendar',
  'places.calendar': 'Calendar',
  'place.events': 'Events calendar',
  'place.note.events': 'Days and deadlines the AI read from the articles. Check before use.',
  'cal.count.one': '1 event or deadline this month',
  'cal.count.other': '{n} events and deadlines this month',
  'cal.prev': 'Previous month',
  'cal.next': 'Next month',
  'cal.thisMonth': 'This month',
  'cal.caption': 'Events and deadlines, {month}',
  'cal.more.one': '+1 more',
  'cal.more.other': '+{n} more',
  'cal.moreLabel': 'Every event of {day} in the list',
  'cal.send': 'The newsletter “{name}” goes out',
  'cal.deadline': 'Sign-up closes',
  'cal.label.event': 'Event {day}: {title}',
  'cal.label.deadline': 'Sign-up closes {day}: {title}',
  'cal.legend.event': 'Event',
  'cal.legend.deadline': 'Last day to sign up',
  'cal.legend.picked': 'Picked for the newsletter',
  'cal.legend.send': 'The newsletter’s send day',
  'cal.emptyTitle': 'No events this month',
  'cal.empty': 'Events come in when the sources bring articles with a date. Event organisers’ sites can be added as sources.',
  'cal.nextMonth': 'Next month',
  'row.event': 'Event {date}',
  'row.eventNow': 'on now',
  'row.signUp': 'sign up by {date}',
  'row.signUpOver': 'sign-up closed {date}',
  'row.deadlineOnly': 'Deadline {date}',
  'row.beforeSend': 'before it goes out',
  'row.byAi': 'Read by the AI:',
  'event.beforeSend': 'It happens before the newsletter goes out on {date}.',
  'event.deadlineBeforeSend': 'Sign-up closes before the newsletter goes out on {date}.',
  'place.suggested': 'Suggested: {section}',
  'place.note.suggested': 'New articles suggested for {section}. Add them to the newsletter, keep them for later or leave them out.',
  'place.empty.suggested': 'Nothing in New is suggested for this section now.',
  'ask.add': 'Add',
  'ask.addLabel': 'Add “{title}” to the newsletter',
  'ask.pickedLabel': '“{title}” is in {section}. Move or take it out',
  'ask.menuTitle': 'Add to the newsletter',
  'ask.menuSection': 'Section',
  'ask.suggestedOption': '{section} (suggested)',
  'ask.removePick': 'Take out of the newsletter',
  'ask.sentPick': 'Sent',
  'ask.next': 'Ask next',
  'ask.recent': 'Asked before',
  'ask.forget': 'Forget the question “{q}”',
  'ask.forgotten': 'Question forgotten.',
  'ask.readerTitle': 'Open an article from the answer',
  'reader.emptyTitle': 'Pick an article from the list',
  'reader.emptyHint': 'Click one to open it. J and K go to the one before and after.',
  'results.noneTitle': 'No matches',
  'place.emptyTitle.inbox': 'All done',
  'place.emptyTitle': 'Nothing here',
  'topic.noneTitle': 'No topics yet',
  'topic.pickTitle': 'Pick a topic',
  'side.editSources': 'Edit the sources',
  'target.planned': 'Goes out {day}, {when}',
  'target.fill': 'Picked by section',
  'status.openSources': 'Open the sources',
};
