// The words of the articles page: the column of topics and views, the list,
// and the article being read. texts.js adds them to the dashboard's own.
// Jira: DM42-80, DM42-31

export const fi = {
  'place.inbox': 'Uudet',
  'place.tag': 'Asiasana: {tag}',
  'place.none': 'Ei aihetta',
  'place.note.inbox': 'Tiivistetyt uutiset ja seurattujen aiheiden opinnäytetyöt viimeiseltä {days} päivältä. Lisää uutiskirjeeseen, säästä myöhemmäksi tai jätä pois.',
  'place.note.topic': 'Kaikki, joilla on jokin aiheen asiasanoista: {terms}.',
  'place.note.tag': 'Kaikki, joilla on YSO-asiasana {tag}.',
  'place.note.none': 'Uutiset, joita mikään aihe ei kata. Täältä näkee, puuttuuko jokin aihe.',
  'place.note.source': 'Kaikki tästä lähteestä.',
  'note.all': 'Kaikki kerätyt artikkelit ja opinnäytetyöt, myös ohitetut ja pois jätetyt.',
  'place.empty.inbox': 'Kaikki uudet on käyty läpi. Uudet tulevat tänne seuraavan tarkistuksen jälkeen.',
  'place.empty.topic': 'Tässä aiheessa ei ole vielä artikkeleita.',
  'place.empty.tag': 'Tällä asiasanalla ei ole artikkeleita.',
  'place.empty.none': 'Kaikilla uutisilla on aihe.',
  'place.empty.source': 'Tästä lähteestä ei ole vielä mitään.',

  'side.label': 'Aiheet ja näkymät',
  'side.open': 'Aiheet',
  'side.close': 'Sulje',
  'side.followed': 'Seuratut aiheet',
  'side.followedHint': 'Näiden aiheiden opinnäytetyöt tulevat Uusiin.',
  'side.other': 'Muut aiheet',
  'side.none': 'Ei aihetta',
  'side.sources': 'Lähteet',
  'side.more': 'Muut näkymät',
  'side.follow': 'Seuraa',
  'side.followLabel': 'Seuraa aihetta {topic}',
  'side.unfollow': 'Lopeta aiheen {topic} seuraaminen',
  'side.newCount': '{n} uutta',

  'target.label': 'Valinnat menevät',
  'target.new': 'Uuteen uutiskirjeeseen',
  'target.newHint': 'Ensimmäinen valinta tekee uuden luonnoksen.',
  'target.picked.one': '1 artikkeli valittu',
  'target.picked.other': '{n} artikkelia valittu',
  'target.open': 'Avaa uutiskirje',

  'search.label': 'Hae',
  'search.hint': 'Hae otsikoista, tiivistelmistä ja asiasanoista',
  'count.one': '1 artikkeli',
  'count.other': '{n} artikkelia',
  'day.today': 'Tänään',
  'day.yesterday': 'Eilen',

  'row.thesis': 'Opinnäytetyö',
  'row.publication': 'Julkaisu',
  'row.waiting': 'Odottaa tekoälyä',
  'row.skipped': 'Ohitettu',
  'row.attention': 'Vaatii huomiota',
  'row.noTags': 'ei asiasanoja',
  'row.tagsComing': 'asiasanat tulossa',
  'row.later': 'Myöhemmin',
  'row.dismissed': 'Ei käytetä',
  'row.sent': 'Lähetetty',

  'reader.empty': 'Valitse artikkeli listasta.',
  'reader.position': '{place} · {n} / {total}',
  'reader.back': 'Takaisin',
  'reader.prev': 'Edellinen',
  'reader.next': 'Seuraava',
  'reader.open': 'Avaa alkuperäinen',
  'reader.topics': 'Aiheet',
  'reader.noTopic': 'Ei aihetta',
  'reader.noLearningTag': 'Ei aihetta, koska oppimisen asiasanaa ei ole',
  'reader.tags': 'Asiasanat',
  'reader.tagsComing': 'Asiasanat tulevat 15 minuutin kuluessa.',
  'reader.tagHint': 'Kaikki, joilla on asiasana {tag}',
  'reader.removeTag': 'Poista asiasana {tag}',
  'reader.addTag': 'Lisää asiasana',
  'reader.addTagHint': 'Kirjoita asiasanan alku',
  'reader.noTerms': 'YSO:sta ei löytynyt tällä alulla.',
  'reader.also': 'myös {name}',
  'reader.signal': 'Signaali: {topic}',
  'reader.summary': 'Tekoälyn tiivistelmä',
  'reader.abstract': 'Tekijän tiivistelmä',
  'reader.licenceOpen': 'Lisenssi {licence}: tekstiä saa käyttää lisenssin ehdoin, kun tekijä ja lähde mainitaan.',
  'reader.licenceClosed': 'Kaikki oikeudet pidätetään, joten uutiskirjeeseen tulee oma tiivistelmä. Tekoäly kirjoittaa sen, kun lisäät työn uutiskirjeeseen.',
  'reader.summaryComing': 'Tekoäly kirjoittaa tiivistelmän 15 minuutin kuluessa.',
  'reader.summariseNow': 'Tiivistä nyt',
  'reader.addTo': 'Lisää uutiskirjeeseen {issue}, osioon:',
  'reader.addToNew': 'Lisää uutiskirjeeseen, osioon:',
  'reader.key': 'Näppäin {key}',
  'reader.suggested': 'Ehdotus · {key}',
  'reader.chosen': 'Valittu',
  'reader.later': 'Myöhemmin',
  'reader.dismiss': 'Ei käytetä',
  'reader.clear': 'Peru päätös',
  'reader.decidedBy': '{name}, {when}',
  'reader.sentIn': 'Lähetetty uutiskirjeessä {issue}.',
  'reader.keysMove': 'liiku',
  'reader.keysAdd': 'lisää',

  'toast.picked': 'Lisätty osioon {section}.',
  'toast.pickedThesis': 'Lisätty osioon {section}. Tekoäly kirjoittaa tiivistelmän 15 minuutin kuluessa.',
  'toast.later': 'Säästetty myöhemmäksi.',
  'toast.dismissed': 'Jätetty pois.',
  'toast.cleared': 'Päätös peruttu.',
  'toast.undo': 'Peru',
  'toast.followed': 'Seuraat aihetta {topic}. Sen opinnäytetyöt tulevat Uusiin.',
  'toast.unfollowed': 'Et enää seuraa aihetta {topic}.',
  'toast.tagAdded': 'Lisätty asiasana {tag}.',
  'toast.tagRemoved': 'Poistettu asiasana {tag}.',

  'status.thesesToday.one': 'Lisäksi 1 opinnäytetyö.',
  'status.thesesToday.other': 'Lisäksi {n} opinnäytetyötä.',

  'error.no_such_topic': 'Tällä numerolla ei ole aihetta.',
  'error.no_such_tag': 'Artikkelilla ei ole tätä asiasanaa.',
  'error.not_a_term': 'YSO:ssa ei ole tällaista asiasanaa.',
  'error.finto_unreachable': 'Finto, josta asiasanat tulevat, ei vastannut. Yritä hetken päästä uudelleen.',
};

export const en = {
  'place.inbox': 'New',
  'place.tag': 'Tag: {tag}',
  'place.none': 'No topic',
  'place.note.inbox': 'Summarised news and the theses of followed topics from the last {days} days. Add to the newsletter, keep for later or leave out.',
  'place.note.topic': 'Everything with one of the topic’s terms: {terms}.',
  'place.note.tag': 'Everything with the YSO term {tag}.',
  'place.note.none': 'News no topic covers. This shows whether a topic is missing.',
  'place.note.source': 'Everything from this source.',
  'note.all': 'Every article and thesis collected, skipped and left-out ones too.',
  'place.empty.inbox': 'You have been through everything new. New articles come here after the next check.',
  'place.empty.topic': 'There are no articles in this topic yet.',
  'place.empty.tag': 'No articles have this tag.',
  'place.empty.none': 'Every news article has a topic.',
  'place.empty.source': 'Nothing from this source yet.',

  'side.label': 'Topics and views',
  'side.open': 'Topics',
  'side.close': 'Close',
  'side.followed': 'Followed topics',
  'side.followedHint': 'Theses in these topics come to New.',
  'side.other': 'Other topics',
  'side.none': 'No topic',
  'side.sources': 'Sources',
  'side.more': 'Other views',
  'side.follow': 'Follow',
  'side.followLabel': 'Follow the topic {topic}',
  'side.unfollow': 'Stop following {topic}',
  'side.newCount': '{n} new',

  'target.label': 'Picks go into',
  'target.new': 'A new newsletter',
  'target.newHint': 'The first pick starts a new draft.',
  'target.picked.one': '1 article picked',
  'target.picked.other': '{n} articles picked',
  'target.open': 'Open the newsletter',

  'search.label': 'Search',
  'search.hint': 'Search titles, summaries and tags',
  'count.one': '1 article',
  'count.other': '{n} articles',
  'day.today': 'Today',
  'day.yesterday': 'Yesterday',

  'row.thesis': 'Thesis',
  'row.publication': 'Publication',
  'row.waiting': 'Waiting for the AI',
  'row.skipped': 'Skipped',
  'row.attention': 'Needs attention',
  'row.noTags': 'no tags',
  'row.tagsComing': 'tags coming',
  'row.later': 'Later',
  'row.dismissed': 'Not used',
  'row.sent': 'Sent',

  'reader.empty': 'Choose an article from the list.',
  'reader.position': '{place} · {n} / {total}',
  'reader.back': 'Back',
  'reader.prev': 'Previous',
  'reader.next': 'Next',
  'reader.open': 'Open the original',
  'reader.topics': 'Topics',
  'reader.noTopic': 'No topic',
  'reader.noLearningTag': 'No topic, because it has no learning tag',
  'reader.tags': 'Tags',
  'reader.tagsComing': 'Tags come within 15 minutes.',
  'reader.tagHint': 'Everything tagged {tag}',
  'reader.removeTag': 'Remove the tag {tag}',
  'reader.addTag': 'Add a tag',
  'reader.addTagHint': 'Type the start of a term',
  'reader.noTerms': 'Nothing in YSO starts like that.',
  'reader.also': 'also {name}',
  'reader.signal': 'Signal: {topic}',
  'reader.summary': 'AI summary',
  'reader.abstract': 'The author’s abstract',
  'reader.licenceOpen': 'Licence {licence}: the text may be used on the licence’s terms, naming the author and the source.',
  'reader.licenceClosed': 'All rights reserved, so the newsletter gets a summary of its own. The AI writes it when you add the thesis to a newsletter.',
  'reader.summaryComing': 'The AI writes the summary within 15 minutes.',
  'reader.summariseNow': 'Summarise now',
  'reader.addTo': 'Add to the newsletter {issue}, in:',
  'reader.addToNew': 'Add to the newsletter, in:',
  'reader.key': 'Key {key}',
  'reader.suggested': 'Suggested · {key}',
  'reader.chosen': 'Chosen',
  'reader.later': 'Later',
  'reader.dismiss': 'Not used',
  'reader.clear': 'Take back',
  'reader.decidedBy': '{name}, {when}',
  'reader.sentIn': 'Sent in the newsletter {issue}.',
  'reader.keysMove': 'move',
  'reader.keysAdd': 'add',

  'toast.picked': 'Added to {section}.',
  'toast.pickedThesis': 'Added to {section}. The AI writes the summary within 15 minutes.',
  'toast.later': 'Kept for later.',
  'toast.dismissed': 'Left out.',
  'toast.cleared': 'Decision taken back.',
  'toast.undo': 'Undo',
  'toast.followed': 'You follow {topic}. Its theses come to New.',
  'toast.unfollowed': 'You no longer follow {topic}.',
  'toast.tagAdded': 'Added the tag {tag}.',
  'toast.tagRemoved': 'Removed the tag {tag}.',

  'status.thesesToday.one': 'And 1 thesis.',
  'status.thesesToday.other': 'And {n} theses.',

  'error.no_such_topic': 'There is no topic with that number.',
  'error.no_such_tag': 'The article has no such tag.',
  'error.not_a_term': 'YSO has no such term.',
  'error.finto_unreachable': 'Finto, where the tags come from, did not answer. Try again in a moment.',
};
