// The newsletter editor's words, in Finnish and English. texts.js adds them
// to the dashboard's own; the rules there apply here too.

export const fi = {
  'editor.title': 'Uutiskirjeen editori',
  'editor.toList': 'Uutiskirjeet',
  'editor.toIssue': 'Takaisin uutiskirjeeseen',
  'editor.noIssue': 'Avaa editori uutiskirjeen sivulta.',
  'editor.rename': 'Nimeä uutiskirje uudelleen',
  'editor.saved': 'Muutokset tallennettu {when}',
  'editor.saving': 'Tallennetaan…',
  'editor.unsaved': 'Tallentamattomia muutoksia',
  'editor.saveFailed': 'Tallennus epäonnistui: {message}',
  'editor.loggedOut': 'Kirjautuminen päättyi. Kirjaudu uudelleen toisessa välilehdessä, niin muutokset tallentuvat.',
  'editor.sendTest': 'Lähetä testi',
  'editor.saveExit': 'Tallenna ja poistu',
  'editor.moreSaving': 'Lisää tallennusvaihtoehtoja',
  'editor.saveAsTemplate': 'Tallenna pohjaksi',
  'editor.changeTemplate': 'Vaihda pohja',
  'editor.backWithoutChecks': 'Tallenna ja palaa tarkistamatta',
  'editor.changeTemplateConfirm': 'Uusi pohja korvaa nykyisen sisällön. Valitut artikkelit lisätään pohjaan uudelleen. Voit perua vaihdon Kumoa-painikkeella vasta, kun pohja on valittu.',
  'editor.saveTemplateTitle': 'Tallenna pohjaksi',
  'editor.saveTemplateHint': 'Pohja tallennetaan ilman artikkeleita. Kun sitä käytetään, sen uutiskirjeen valitut artikkelit lisätään omiin osioihinsa.',
  'editor.templateSaved': 'Tallennettu pohjaksi: {name}',
  'editor.saveSectionTitle': 'Tallenna osio',
  'editor.saveSectionHint': 'Tallennettu osio löytyy Osiot-paneelin Tallennetut-välilehdeltä, ja sen voi lisätä mihin tahansa uutiskirjeeseen.',
  'editor.sectionSaved': 'Osio tallennettu: {name}',
  'editor.nameLabel': 'Nimi',
  'editor.newSection': 'Uusi osio',
  'editor.view': 'Näkymä',
  'editor.desktop': 'Tietokone',
  'editor.mobile': 'Puhelin',
  'editor.undo': 'Kumoa',
  'editor.redo': 'Tee uudelleen',
  'editor.comments': 'Kommentit',
  'editor.preview': 'Esikatsele',
  'editor.canvas': 'Uutiskirje',
  'editor.conflictTitle': 'Joku muu tallensi välillä',
  'editor.conflictText': '{name} tallensi uutiskirjeen {when}, sen jälkeen kun avasit sen. Kumpi versio jää?',
  'editor.conflictReload': 'Lataa heidän versionsa',
  'editor.conflictOverwrite': 'Pidä minun versioni',
  'editor.exitErrors.one': 'Löysimme 1 asian, joka kaipaa huomiota',
  'editor.exitErrors.other': 'Löysimme {n} asiaa, jotka kaipaavat huomiota',
  'editor.exitErrorsLead': 'Uutiskirje on tallennettu. Nämä pitää korjata ennen kuin sen voi viedä Mailchimpiin:',
  'editor.exitAnyway': 'Tallenna ja poistu',
  'editor.resolve': 'Korjaa nyt',
  'editor.subjectTitle': 'Aiherivi ja esikatseluteksti',

  'rail.label': 'Paneelit',
  'rail.blocks': 'Lohkot',
  'rail.sections': 'Osiot',
  'rail.styles': 'Tyylit',
  'rail.check': 'Tarkistus',

  'block.text': 'Teksti',
  'block.image': 'Kuva',
  'block.button': 'Painike',
  'block.divider': 'Erotin',
  'block.spacer': 'Väli',
  'block.social': 'Some',
  'block.video': 'Video',
  'block.logo': 'Logo',
  'block.footer': 'Alatunniste',
  'block.columns': 'Sarakkeet',
  'block.article': 'Artikkeli',
  'block.link': 'Linkki',

  'tile.image': 'Kuva',
  'tile.heading': 'Otsikko',
  'tile.paragraph': 'Kappale',
  'tile.button': 'Painike',
  'tile.divider': 'Erotin',
  'tile.spacer': 'Väli',
  'tile.video': 'Video',
  'tile.social': 'Some',
  'tile.logo': 'Logo',
  'tile.footer': 'Alatunniste',

  'blocks.help': 'Näin käytät editoria',
  'blocks.title': 'Sisältölohkot',
  'blocks.lead': 'Vedä lohko kirjeeseen, tai napsauta sitä, niin se tulee valitun kohdan alle.',
  'blocks.tileHint': '{name}: vedä kirjeeseen tai napsauta',
  'blocks.articles': 'Valitut artikkelit',
  'blocks.articlesLead': 'Nämä on valittu Artikkelit-sivulla, mutta ne eivät ole vielä kirjeessä. Napsauta, niin artikkeli menee omaan osioonsa, tai vedä se haluamaasi kohtaan.',
  'blocks.allPlaced': 'Kaikki valitut artikkelit ovat kirjeessä.',
  'blocks.noneTicked': 'Valitse artikkeleita Artikkelit-sivulla, niin ne tulevat tähän.',
  'blocks.articleHint': 'Napsauta: omaan osioonsa. Vedä: haluamaasi kohtaan.',
  'blocks.addAll': 'Lisää kaikki osioihinsa',
  'blocks.addedAll.one': '1 artikkeli lisätty',
  'blocks.addedAll.other': '{n} artikkelia lisätty',
  'blocks.columnsTitle': 'Sarakkeet',
  'blocks.columnsLead': 'Vedä sarakeasettelu kirjeeseen ja lohkoja sen sarakkeisiin.',
  'blocks.columnsHint': 'Sarakkeet {name}',
  'blocks.columns': 'Sarakkeet {layout}',
  'blocks.oneColumn': '1 sarake',

  'canvas.typeHere': 'Kirjoita tähän…',
  'canvas.addImage': 'Lisää kuva: valitse tämä lohko ja lataa kuva vasemmalta.',
  'canvas.addLogo': 'Lisää logo',
  'canvas.addSocial': 'Lisää somelinkit',
  'canvas.addVideo': 'Lisää videon osoite vasemmalta.',
  'canvas.addArticleImage': 'Lisää kuva: valitse artikkeli ja lisää kuva vasemmalta.',
  'canvas.dropHere': 'Vedä lohko tähän',
  'canvas.emptySection': 'Tyhjä osio. Vedä lohkoja tähän.',
  'canvas.noArticles': 'Tähän osioon ei ole valittu artikkeleita, joten se jätetään pois kirjeestä.',
  'canvas.dragToMove': 'Vedä siirtääksesi',
  'canvas.move': 'Siirrä',
  'canvas.duplicate': 'Monista',
  'canvas.comment': 'Kommentoi',
  'canvas.delete': 'Poista',
  'canvas.markChecked': 'Merkitse tarkistetuksi',
  'canvas.markUnchecked': 'Tarkistettu. Napsauta, niin merkintä poistuu.',
  'canvas.sectionUp': 'Siirrä osio ylemmäs',
  'canvas.sectionDown': 'Siirrä osio alemmas',
  'canvas.sectionMore': 'Lisää toimintoja',

  'tt.label': 'Tekstin muotoilu',
  'tt.format': 'Tekstin tyyli',
  'tt.format.p': 'Kappale',
  'tt.format.h1': 'Otsikko 1',
  'tt.format.h2': 'Otsikko 2',
  'tt.format.h3': 'Otsikko 3',
  'tt.format.h4': 'Otsikko 4',
  'tt.font': 'Fontti',
  'tt.fontDefault': 'Oletusfontti',
  'tt.size': 'Fonttikoko',
  'tt.sizeUp': 'Suurempi',
  'tt.sizeDown': 'Pienempi',
  'tt.colour': 'Tekstin väri',
  'tt.highlight': 'Korostusväri',
  'tt.noHighlight': 'Ei korostusta',
  'tt.bold': 'Lihavointi',
  'tt.italic': 'Kursiivi',
  'tt.underline': 'Alleviivaus',
  'tt.strike': 'Yliviivaus',
  'tt.link': 'Linkki',
  'tt.align': 'Tasaus',
  'tt.alignLeft': 'Vasemmalle',
  'tt.alignCenter': 'Keskelle',
  'tt.alignRight': 'Oikealle',
  'tt.alignJustify': 'Molempiin reunoihin',
  'tt.lineHeight': 'Riviväli',
  'tt.letterSpacing': 'Merkkiväli',
  'tt.bullets': 'Luettelo',
  'tt.numbers': 'Numeroitu luettelo',
  'tt.more': 'Lisää',
  'tt.clear': 'Poista muotoilu',
  'tt.titleNote': 'Otsikon ulkoasu tulee Tyylit-paneelista (Otsikko 3). Kirjoita otsikko suoraan tähän.',
  'tt.buttonNote': 'Kirjoita painikkeen teksti. Värin, muodon ja koon voit vaihtaa vasemmalta, Tyylit-välilehdeltä.',

  'merge.fname': 'Lukijan etunimi',
  'merge.lname': 'Lukijan sukunimi',
  'merge.email': 'Lukijan sähköpostiosoite',
  'merge.date': 'Tämä päivä',
  'merge.year': 'Kuluva vuosi',
  'merge.company': 'Yhdistyksen nimi',
  'merge.unsub': 'Peru tilaus -linkki',
  'merge.profile': 'Päivitä tietosi -linkki',
  'merge.archive': 'Näytä selaimessa -linkki',

  'link.title': 'Linkki',
  'link.to': 'Linkin kohde',
  'link.kind': 'Linkin tyyppi',
  'link.kind.web': 'Verkkosivu',
  'link.kind.email': 'Sähköposti',
  'link.kind.phone': 'Puhelin',
  'link.placeholder.web': 'https://',
  'link.placeholder.email': 'nimi@esimerkki.fi',
  'link.placeholder.phone': '+358 40 123 4567',
  'link.address': 'Osoite',
  'link.newTab': 'Avaa uuteen välilehteen',
  'link.save': 'Tallenna',
  'link.remove': 'Poista linkki',

  'control.more': 'Lisää',
  'control.less': 'Vähemmän',
  'control.colourCode': 'Värikoodi',
  'control.pickColour': 'Valitse väri',
  'control.noColour': 'Ei väriä',
  'control.allSides': 'Kaikki sivut',
  'control.sameAllSides': 'Sama kaikille sivuille',
  'control.top': 'Ylä',
  'control.bottom': 'Ala',
  'control.left': 'Vasen',
  'control.right': 'Oikea',

  'align.left': 'Vasemmalle',
  'align.center': 'Keskelle',
  'align.right': 'Oikealle',
  'border.none': 'Ei reunaa',
  'border.solid': 'Yhtenäinen',
  'border.dashed': 'Katkoviiva',
  'border.dotted': 'Pisteviiva',

  'settings.back': 'Takaisin',
  'settings.tab.content': 'Sisältö',
  'settings.tab.styles': 'Tyylit',
  'settings.section': 'Osio',
  'settings.blockBackground': 'Lohkon taustaväri',
  'settings.border': 'Reunus',
  'settings.borderStyle': 'Reunan tyyli',
  'settings.borderWidth': 'Paksuus',
  'settings.borderColour': 'Reunan väri',
  'settings.radius': 'Pyöristetyt kulmat',
  'settings.padding': 'Täyte',
  'settings.margin': 'Marginaali',
  'settings.align': 'Tasaus',
  'settings.noImage': 'Vedä kuva tähän tai valitse',
  'settings.upload': 'Lataa kuva',
  'settings.library': 'Kuvapankki',
  'settings.replace': 'Vaihda kuva',
  'settings.removeImage': 'Poista kuva',
  'settings.size': 'Koko',
  'settings.sizeOriginal': 'Alkuperäinen',
  'settings.sizeFill': 'Täysi leveys',
  'settings.sizeScale': 'Skaalaa',
  'settings.scale': 'Leveys',
  'settings.link': 'Linkki',
  'settings.alt': 'Vaihtoehtoinen teksti',
  'settings.altPlaceholder': 'Kerro, mitä kuvassa on',
  'settings.altHint': 'Näkyy, jos kuva ei lataudu, ja ruudunlukija lukee sen näkövammaisille lukijoille.',
  'settings.logoWidth': 'Leveys',
  'settings.buttonText': 'Painikkeen teksti',
  'settings.shape': 'Muoto',
  'settings.square': 'Suorakulmio',
  'settings.round': 'Pyöristetty',
  'settings.pill': 'Kapseli',
  'settings.buttonColour': 'Painikkeen väri',
  'settings.textColour': 'Tekstin väri',
  'settings.linkColour': 'Linkin väri',
  'settings.font': 'Fontti',
  'settings.fontSize': 'Fonttikoko',
  'settings.bold': 'Lihavointi',
  'settings.italic': 'Kursiivi',
  'settings.letterSpacing': 'Merkkiväli',
  'settings.buttonSize': 'Painikkeen koko',
  'settings.small': 'Pieni',
  'settings.medium': 'Keskikoko',
  'settings.large': 'Suuri',
  'settings.fullWidth': 'Koko leveys',
  'settings.lineStyle': 'Viivan tyyli',
  'settings.lineColour': 'Viivan väri',
  'settings.thickness': 'Paksuus',
  'settings.height': 'Korkeus',
  'settings.network': 'Palvelu',
  'settings.up': 'Ylemmäs',
  'settings.remove': 'Poista',
  'settings.socialLabel': 'Teksti',
  'settings.addSocial': 'Lisää linkki',
  'settings.display': 'Näytä',
  'settings.displayIcon': 'Kuvake',
  'settings.displayBoth': 'Kuvake ja teksti',
  'settings.displayText': 'Teksti',
  'settings.iconStyle': 'Kuvakkeiden tyyli',
  'settings.iconColour': 'Värillinen',
  'settings.iconDark': 'Tumma',
  'settings.iconLight': 'Vaalea',
  'settings.layout': 'Asettelu',
  'settings.horizontal': 'Vaaka',
  'settings.vertical': 'Pysty',
  'settings.iconSize': 'Koko',
  'settings.spacing': 'Väli',
  'settings.videoUrl': 'Videon osoite',
  'settings.videoHint': 'YouTube- tai Vimeo-video. Esikatselukuva haetaan itsestään, ja kuvaa napsauttamalla video avautuu.',
  'settings.videoFetching': 'Haetaan esikatselukuvaa…',
  'settings.thumbnail': 'Esikatselukuva',
  'settings.columnCount': 'Sarakkeiden määrä',
  'settings.columnLayout': 'Leveyksien suhde',
  'settings.equal': 'Tasan',
  'settings.mobile': 'Puhelimessa',
  'settings.stack': 'Allekkain',
  'settings.stackReverse': 'Allekkain, käänteisesti',
  'settings.sideBySide': 'Vierekkäin',
  'settings.valign': 'Pystytasaus',
  'settings.top': 'Ylös',
  'settings.middle': 'Keskelle',
  'settings.bottom': 'Alas',
  'settings.columnBackground': 'Sarakkeiden taustaväri',
  'settings.checked': 'Tarkistettu',
  'settings.checkedHint': 'Merkitse, kun olet lukenut tekoälyn kirjoittaman tekstin ja korjannut sen tarvittaessa. Tarkistamaton teksti näkyy kirjeessä oranssilla katkoviivalla.',
  'settings.original': 'Alkuperäinen artikkeli',
  'settings.foreignTitle': 'Otsikko on vielä alkuperäisellä kielellä ({lang}). Suomenna se, niin kirje on kauttaaltaan suomeksi.',
  'settings.title': 'Otsikko',
  'settings.linkTitle': 'Otsikko on linkki artikkeliin',
  'settings.showSource': 'Näytä lähderivi',
  'settings.articleButton': 'Painike',
  'settings.showButton': 'Näytä painike',
  'settings.articleLayout': 'Asettelu',
  'settings.layoutText': 'Teksti',
  'settings.layoutLeft': 'Kuva vasemmalla',
  'settings.layoutRight': 'Kuva oikealla',
  'settings.layoutTop': 'Kuva ylhäällä',
  'settings.articleLook': 'Artikkelien ulkoasu',
  'settings.articleLookHint': 'Koskee kaikkia tämän osion artikkeleita.',
  'settings.lookPlain': 'Tavallinen',
  'settings.lookLarge': 'Iso otsikko',
  'settings.lookCard': 'Kortti',
  'settings.lookBar': 'Otsikkopalkki',
  'settings.cardColour': 'Kortin väri',
  'settings.barColour': 'Palkin väri',
  'settings.lookDefaultColour': 'Oletus',
  'settings.newArticleLayout': 'Uusien artikkelien asettelu',
  'settings.newArticleLayoutHint': 'Koskee artikkeleita, jotka tulevat tähän osioon tästä eteenpäin. Yksittäisen artikkelin asettelun voi vaihtaa sen omista asetuksista.',
  'settings.anchor': 'Linkki tähän osioon',
  'settings.spaceAbove': 'Väli yläpuolella',
  'settings.spaceAboveHint': 'Valkoinen väli ennen osiota, jotta värilliset osiot erottuvat toisistaan.',
  'settings.anchorHint': 'Lyhyt nimi, esimerkiksi tapahtumat. Linkki #tapahtumat vie lukijan tähän osioon, jos hänen sähköpostiohjelmansa sallii sen.',
  'settings.articleImage': 'Artikkelin kuva',
  'settings.imageRights': 'Käytä vain kuvia, joihin yhdistyksellä on oikeus. Julkaisijan sivun kuvaa ei saa kopioida ilman lupaa.',
  'settings.moveTo': 'Osio',
  'settings.footerNote': 'Alatunnisteessa pitää olla linkki, josta lukija voi perua tilauksen. Mailchimp vaatii sen, eikä lähetä kirjettä ilman sitä.',
  'settings.footerHasUnsub': 'Peruutuslinkki on mukana.',
  'settings.footerNoUnsub': 'Peruutuslinkki puuttuu.',
  'settings.addUnsub': 'Lisää peruutuslinkki',
  'settings.footerHasAddress': 'Postiosoite on mukana.',
  'settings.footerNoAddress': 'Postiosoite puuttuu. Mailchimp vaatii sen.',
  'settings.addAddress': 'Lisää postiosoite',
  'settings.resetFooter': 'Palauta oletusteksti',
  'settings.clearStyles': 'Tyhjennä tyylit',
  'settings.applyAll': 'Käytä kaikkiin',
  'settings.appliedAll': 'Tyylit käytössä kaikissa lohkoissa: {type}',
  'settings.sectionName': 'Osion nimi',
  'settings.sectionBackground': 'Osion tausta',
  'settings.sectionBackgroundHint': 'Väri koko leveydelle, myös sisällön sivuille.',
  'settings.contentBackground': 'Sisällön tausta',
  'settings.sectionText': 'Teksti',
  'settings.sectionLink': 'Linkit',
  'settings.samePage': 'Sama kuin sivun tausta',
  'settings.sameEmail': 'Sama kuin kirjeen tyyleissä',
  'settings.saveSection': 'Tallenna osio',
  'settings.duplicateSection': 'Monista',
  'settings.deleteSection': 'Poista osio',

  'sections.title': 'Osiot',
  'sections.lead': 'Kirje koostuu osioista. Järjestä ne, lisää valmiita tai käytä tallentamiasi.',
  'sections.tab.manage': 'Hallitse',
  'sections.tab.prebuilt': 'Valmiit',
  'sections.tab.trends': 'Trendit',
  'sections.trendsLead': 'Signaalien haku {date}: aiheet, joista lähteet kirjoittivat moneen kertaan. Vedä aihe kirjeeseen tai paina sitä, niin se tulee Nostoja kentältä -osion perään. Laatikossa on muutama aiheen juttu, ja te kirjoitatte, miksi aihe on nyt ajankohtainen.',
  'sections.trendsNone': 'Signaaleja ei ole vielä haettu, tai mikään aihe ei toistunut. Ne haetaan maanantaisin, ja Artikkelit-sivulla voi hakea heti.',
  'sections.trendsCount.one': '{n} juttu',
  'sections.trendsCount.other': '{n} juttua',
  'sections.tab.saved': 'Tallennetut',
  'sections.drag': 'Vedä järjestääksesi',
  'sections.up': 'Ylemmäs',
  'sections.down': 'Alemmas',
  'sections.more': 'Lisää toimintoja: {name}',
  'sections.notSent': 'ei kirjeessä',
  'sections.rename': 'Nimeä uudelleen',
  'sections.duplicate': 'Monista',
  'sections.save': 'Tallenna osio',
  'sections.delete': 'Poista',
  'sections.addBlank': 'Lisää tyhjä osio',
  'sections.addHint': 'Vedä kirjeeseen tai napsauta',
  'sections.group.header': 'Ylätunniste',
  'sections.group.hero': 'Esittely',
  'sections.group.articles': 'Artikkelit',
  'sections.group.text': 'Teksti ja painike',
  'sections.group.gallery': 'Kuvat',
  'sections.group.signup': 'Liittyminen ja tilaus',
  'sections.group.event': 'Tapahtuma',
  'sections.group.columns': 'Nostot sarakkeissa',
  'sections.group.footer': 'Alatunniste',
  'sections.loading': 'Haetaan…',
  'sections.search': 'Hae nimellä',
  'sections.noSaved': 'Tallennettuja osioita ei vielä ole. Valitse osio kirjeestä ja valitse Tallenna osio.',
  'sections.savedMore': 'Lisää toimintoja',
  'sections.renameSaved': 'Nimeä tallennettu osio',
  'sections.deleteSavedConfirm': 'Poistetaanko tallennettu osio {name}? Kirjeissä jo oleviin osioihin tämä ei vaikuta.',

  'styles.title': 'Kirjeen tyylit',
  'styles.lead': 'Koko kirjeen ulkoasu. Yksittäisen lohkon tai osion voi muuttaa sen omista asetuksista.',
  'styles.background': 'Tausta',
  'styles.text': 'Teksti',
  'styles.link': 'Linkit',
  'styles.button': 'Painikkeet',
  'styles.divider': 'Erottimet',
  'styles.image': 'Kuvat',
  'styles.logo': 'Logo',
  'styles.contentColour': 'Sisällön väri',
  'styles.pageColour': 'Taustaväri',
  'styles.margin': 'Tila ylä- ja alapuolella',
  'styles.marginHint': 'Kuinka paljon taustaa näkyy kirjeen ylä- ja alapuolella.',
  'styles.mobilePadding': 'Sivutäyte puhelimessa',
  'styles.mobilePaddingHint': 'Puhelimessa tekstin reunoille jää näin paljon tilaa.',
  'styles.textKind': 'Tekstin laji',
  'styles.font': 'Fontti',
  'styles.letterSpacing': 'Merkkiväli',
  'styles.textColour': 'Tekstin väri',
  'styles.size': 'Koko',
  'styles.mobileSize': 'Koko puhelimessa',
  'styles.lineHeight': 'Riviväli',
  'styles.spacing': 'Kappaleväli',
  'styles.linkColour': 'Linkin väri',
  'styles.underline': 'Alleviivaa linkit',

  'check.title': 'Tarkistus',
  'check.lead': 'Virheet pitää korjata ennen kuin kirjeen voi viedä Mailchimpiin tai lähettää testinä. Huomiot kannattaa katsoa.',
  'check.errorCount.one': '1 virhe',
  'check.errorCount.other': '{n} virhettä',
  'check.warningCount.one': '1 huomio',
  'check.warningCount.other': '{n} huomiota',
  'check.allGood': 'Kaikki kunnossa.',
  'check.show': 'Näytä',
  'check.open': 'Avaa',
  'check.markChecked': 'Merkitse tarkistetuksi',
  'check.markAll': 'Merkitse kaikki tarkistetuiksi',
  'check.markAllConfirm': 'Oletko lukenut kaikki {n} artikkelia? Merkintä kertoo, että ihminen on tarkistanut tekoälyn tekstin.',
  'check.insert': 'Lisää kirjeeseen',
  'check.insertAll': 'Lisää kaikki osioihinsa',
  'check.removeFromEmail': 'Poista kirjeestä',
  'check.addUnsub': 'Lisää peruutuslinkki',
  'check.addSubject': 'Kirjoita aiherivi',
  'check.noAddress': 'ei osoitetta',
  'check.links': 'Linkit',
  'check.mergeTags': 'Yhdistämiskentät',
  'check.mergeTagsHint': 'Mailchimp täyttää nämä jokaiselle lukijalle lähetyksen yhteydessä. Esikatselussa ne näkyvät sellaisinaan.',
  'check.unchecked.one': '1 artikkeli tarkistamatta',
  'check.unchecked.other': '{n} artikkelia tarkistamatta',
  'check.uncheckedHint': 'Lue tekoälyn kirjoittama teksti ja merkitse artikkeli tarkistetuksi. Merkintä kertoo, että ihminen on lukenut tekstin.',
  'check.uncheckedDraft.one': '1 tekoälyn luonnos tarkistamatta',
  'check.uncheckedDraft.other': '{n} tekoälyn luonnosta tarkistamatta',
  'check.uncheckedDraftHint': 'Lue tekoälyn kirjoittama luonnos, korjaa tarvittaessa ja merkitse se tarkistetuksi.',
  'check.placeholders.one': '1 kohta paikkamerkkitekstiä',
  'check.placeholders.other': '{n} kohtaa paikkamerkkitekstiä',
  'check.placeholdersHint': 'Korvaa tai poista malliteksti, kuten "Kirjoita tähän…" tai "Painikkeen teksti". Kirje viedään Mailchimpiin vasta, kun sitä ei ole jäljellä.',
  'check.unsubscribe.one': 'Peruutuslinkki puuttuu',
  'check.unsubscribe.other': 'Peruutuslinkki puuttuu',
  'check.unsubscribeHint': 'Jokaisessa kirjeessä pitää olla linkki, josta lukija voi perua tilauksen. Mailchimp vaatii sen.',
  'check.address.one': 'Postiosoite puuttuu',
  'check.address.other': 'Postiosoite puuttuu',
  'check.addressHint': 'Mailchimp vaatii jokaiseen kirjeeseen lähettäjän postiosoitteen. Merkintä *|LIST:ADDRESSLINE|* hakee sen Mailchimpin yleisön asetuksista.',
  'check.addAddress': 'Lisää osoite alatunnisteeseen',
  'check.subject.one': 'Aiherivi puuttuu',
  'check.subject.other': 'Aiherivi puuttuu',
  'check.subjectHint': 'Aiherivi näkyy lukijan postilaatikossa kirjeen otsikkona.',
  'check.foreign.one': '1 otsikko alkuperäisellä kielellä',
  'check.foreign.other': '{n} otsikkoa alkuperäisellä kielellä',
  'check.foreignHint': 'Otsikko on vielä sellaisenaan kuin julkaisija sen kirjoitti. Suomenna se, jos kirje on muuten suomeksi.',
  'check.missing.one': '1 valittu artikkeli ei ole kirjeessä',
  'check.missing.other': '{n} valittua artikkelia ei ole kirjeessä',
  'check.missingHint': 'Nämä on valittu Artikkelit-sivulla mutta eivät ole vielä kirjeessä.',
  'check.orphans.one': '1 artikkeli ei ole enää valittuna',
  'check.orphans.other': '{n} artikkelia ei ole enää valittuna',
  'check.orphansHint': 'Nämä on poistettu valinnoista Artikkelit-sivulla, mutta ne ovat yhä kirjeessä.',
  'check.alt.one': '1 kuva ilman vaihtoehtoista tekstiä',
  'check.alt.other': '{n} kuvaa ilman vaihtoehtoista tekstiä',
  'check.altHint': 'Kerro lyhyesti, mitä kuvassa on. Teksti näkyy, jos kuva ei lataudu, ja ruudunlukija lukee sen.',
  'check.emptyImages.one': '1 kuvapaikka ilman kuvaa',
  'check.emptyImages.other': '{n} kuvapaikkaa ilman kuvaa',
  'check.emptyImagesHint': 'Esikatselussa niiden kohdalla on harmaa laatikko. Lähtevästä kirjeestä ne jäävät pois: kuvalohko kokonaan ja artikkeli pelkkänä tekstinä. Lisää kuva, poista lohko tai valitse artikkelin asetteluksi Teksti.',
  'check.emptyLinks.one': '1 linkki ilman osoitetta',
  'check.emptyLinks.other': '{n} linkkiä ilman osoitetta',
  'check.emptyLinksHint': 'Linkki tai painike, jolla ei ole osoitetta, ei vie lukijaa minnekään.',
  'check.size.one': 'Kirje on {kb} kt: Gmail katkaisee sen',
  'check.size.other': 'Kirje on {kb} kt: Gmail katkaisee sen',
  'check.sizeHint': 'Gmail näyttää vain 102 kt ja piilottaa loput, peruutuslinkki mukaan lukien. Lyhennä kirjettä.',

  'linkKind.text': 'Tekstilinkki',
  'linkKind.button': 'Painike',
  'linkKind.image': 'Kuvan linkki',
  'linkKind.video': 'Video',
  'linkKind.social': 'Somelinkki',
  'linkKind.title': 'Otsikon linkki',

  'dialog.close': 'Sulje',
  'dialog.cancel': 'Peruuta',
  'dialog.ok': 'OK',
  'dialog.save': 'Tallenna',
  'dialog.confirm': 'Oletko varma?',

  'library.title': 'Kuvapankki',
  'library.scope.all': 'Kaikki kuvat',
  'library.scope.issue': 'Tämän kirjeen kuvat',
  'library.search': 'Hae nimellä',
  'library.upload': 'Lataa kuvia',
  'library.dropHint': 'Voit myös vetää kuvia tähän ikkunaan. Kuvat pienennetään sähköpostiin sopiviksi, ja kameran tiedot, kuten kuvauspaikka, poistetaan.',
  'library.loading': 'Haetaan…',
  'library.uploading': 'Ladataan…',
  'library.uploaded.one': '1 kuva ladattu',
  'library.uploaded.other': '{n} kuvaa ladattu',
  'library.uploadFailed': 'Kuvan lataus epäonnistui.',
  'library.empty': 'Kuvia ei vielä ole',
  'library.nothingFound': 'Ei osumia',
  'library.emptyHint': 'Lataa kuvia tietokoneelta, niin ne ovat käytettävissä kaikissa uutiskirjeissä.',
  'library.pick': 'Valitse tämä kuva',
  'library.delete': 'Poista kuva',
  'library.deleteConfirm': 'Poistetaanko kuva {name}? Se katoaa myös lähetetyistä kirjeistä, joissa sitä on käytetty.',
  'library.deleted': 'Kuva poistettu',
  'library.showing': 'Näytetään {from}–{to} / {total}',
  'library.page': 'Sivu {page} / {pages}',
  'library.previous': 'Edellinen',
  'library.next': 'Seuraava',

  'preview.title': 'Esikatselu',
  'preview.frameTitle': 'Kirje sellaisena kuin lukija sen näkee',
  'preview.sendTest': 'Lähetä testi',
  'preview.pictureHere': 'Kuva tulee tähän',
  'preview.videoHere': 'Video tulee tähän',
  'preview.logoHere': 'Logo',
  'preview.info': 'Sähköpostin tiedot',
  'preview.from': 'Lähettäjä',
  'preview.fromMailchimp': 'Asetetaan Mailchimpissa',
  'preview.subject': 'Aiherivi',
  'preview.preheader': 'Esikatseluteksti',
  'preview.noSubject': 'Aiherivi puuttuu',
  'preview.noPreheader': 'Ei esikatselutekstiä',
  'preview.checkLinks': 'Tarkista linkit ({checked}/{total})',
  'preview.linksChecked': '{checked}/{total} linkkiä tarkistettu',
  'preview.linksHint': 'Avaa jokainen linkki ja katso, että se vie oikeaan paikkaan.',
  'preview.noLinks': 'Kirjeessä ei ole linkkejä.',
  'preview.linkDetails': 'Linkin tiedot',
  'preview.openLink': 'Avaa linkki',
  'preview.markChecked': 'Merkitse tarkistetuksi',
  'preview.editLink': 'Muokkaa',
  'preview.linkOf': 'Linkki {n} / {total}',
  'preview.mergeLink': 'Mailchimp vaihtaa tämän lukijakohtaiseksi linkiksi lähetyksessä.',
  'preview.emptyLink': 'Linkillä ei ole osoitetta.',
  'preview.size': 'Kirjeen koko',
  'preview.clipped': 'Gmail katkaisee yli 102 kt kirjeet. Lyhennä kirjettä.',
  'preview.notClipped': 'Gmail näyttää koko kirjeen.',

  'chooser.title': 'Valitse pohja',
  'chooser.lead': 'Kirje alkaa pohjasta. Valitut artikkelit lisätään siihen omiin osioihinsa, ja kaikkea voi muuttaa myöhemmin.',
  'chooser.back': 'Takaisin',
  'chooser.tab.builtin': 'Valmiit pohjat',
  'chooser.tab.saved': 'Tallennetut',
  'chooser.tab.past': 'Aiemmat uutiskirjeet',
  'chooser.use': 'Käytä tätä',
  'chooser.preview': 'Esikatsele',
  'chooser.recommended': 'Suositeltu',
  'chooser.loading': 'Haetaan…',
  'chooser.noSaved': 'Tallennettuja pohjia ei vielä ole. Editorissa: Tallenna ja poistu ▾ → Tallenna pohjaksi.',
  'chooser.noPast': 'Aiempia uutiskirjeitä ei vielä ole.',
  'chooser.pastLead': 'Sama ulkoasu ja tekstit, tämän kirjeen artikkeleilla.',
  'chooser.sentOn': 'Lähetetty {date}',
  'chooser.draft': 'Luonnos',

  'template.eok': 'Yhdistyksen uutiskirje',
  'template.eok.lead': 'Kuten Mailchimpista lähtevä uutiskirje: banneri, omat uutiset kuvin, tapahtumat ja nostot vaaleanpunaisissa laatikoissa, vinkit, Learning Factory ja Liity jäseneksi.',
  'template.jasenkirje': 'Jäsenkirje',
  'template.jasenkirje.lead': 'Kuten jäsenkirje: sisällysluettelo, iso kuva, Tutustu ainakin näihin, osiot magentan palkkien alla ja otsikot vihreissä palkeissa.',
  'template.simple': 'Yksinkertainen',
  'template.simple.lead': 'Valkoinen ja selkeä, vähän värejä. Sopii lyhyeen kirjeeseen.',
  'template.visual': 'Kuvallinen',
  'template.visual.lead': 'Logo, iso pääkuva ja esittely kahdessa sarakkeessa.',
  'template.blank': 'Aloita tyhjästä',
  'template.blank.lead': 'Ylätunniste, tyhjä sisältöosio ja alatunniste. Rakenna loput lohkoista.',
  'chooser.all': 'Kaikki',
  'chooser.filter': 'Näytä pohjat',
  'chooser.group.newsletters': 'Uutiskirjeet',
  'chooser.group.events': 'Tapahtumat',
  'chooser.group.announcements': 'Tiedotteet ja kyselyt',
  'chooser.group.membership': 'Jäsenyys',
  'chooser.group.training': 'Koulutukset',
  'chooser.group.greetings': 'Tervehdykset',
  'chooser.group.layouts': 'Perusasettelut',
  'template.letter': 'Kirje jäsenille',
  'template.letter.lead': 'Henkilökohtainen kirje: banneri, teksti ja allekirjoitus kuvan kanssa.',
  'template.join': 'Liity jäseneksi',
  'template.join.lead': 'Kutsu liittymään: miksi kannattaa, kolme jäsenetua ja painike yhdistyksen jäsenyyssivulle.',
  'template.event': 'Tapahtumakutsu',
  'template.event.lead': 'Pääkuva, tapahtuman tiedot, ohjelma, puhujat ja ilmoittautumispainike.',
  'template.webinar': 'Webinaarikutsu',
  'template.webinar.lead': 'Ajankohta, mitä osallistuja oppii, puhuja ja ilmoittautuminen.',
  'template.reminder': 'Muistutus',
  'template.reminder.lead': 'Lyhyt muistutus juuri ennen tapahtumaa: aika, paikka ja liittymispainike.',
  'template.thanks': 'Kiitos osallistumisesta',
  'template.thanks.lead': 'Tapahtuman jälkeen: tallenne, materiaalit, kuvia ja palautekysely.',
  'template.announce': 'Tiedote',
  'template.announce.lead': 'Yksi tärkeä asia: iso kuva, otsikko, teksti ja painike.',
  'template.meeting': 'Kokouskutsu',
  'template.meeting.lead': 'Kutsu yhdistyksen kokoukseen: aika, paikka, esityslista ja ilmoittautuminen.',
  'template.survey': 'Kysely',
  'template.survey.lead': 'Pyydä jäseniltä palautetta tai mielipidettä yhdellä selkeällä painikkeella.',
  'template.course': 'Koulutustarjonta',
  'template.course.lead': 'Johdanto, kolme koulutusta rinnakkain, osallistujan palaute ja painike.',
  'template.training': 'Koulutus',
  'template.training.lead': 'Yksi koulutus tarkemmin: tiedot, sisältö, kouluttaja ja ilmoittautuminen.',
  'template.welcome': 'Tervetuloa jäseneksi',
  'template.welcome.lead': 'Uudelle jäsenelle: jäsenedut, ensimmäiset askeleet ja yhteyshenkilö.',
  'template.greeting': 'Juhlatervehdys',
  'template.greeting.lead': 'Kuva ja muutama lämmin sana keskitettynä. Sopii jouluun ja muihin juhliin.',
  'template.onecol': 'Yksi sarake',
  'template.onecol.lead': 'Logo, kuva, teksti ja painike allekkain. Helppo muokata mihin tahansa.',
  'template.twocol': 'Kaksi saraketta',
  'template.twocol.lead': 'Neljä nostoa kahdessa sarakkeessa, kussakin kuva, teksti ja painike.',
  'template.threecol': 'Kolme saraketta',
  'template.threecol.lead': 'Kolme lyhyttä nostoa rinnakkain kuvineen.',
  'template.zigzag': 'Kuva ja teksti vuorotellen',
  'template.zigzag.lead': 'Kuva ja teksti vierekkäin, ja puolet vaihtuvat joka rivillä.',
  'template.plain': 'Pelkkä teksti',
  'template.plain.lead': 'Kuin tavallinen sähköposti: ei värejä eikä kuvia.',

  'comments.title': 'Kommentit',
  'comments.tab.open': 'Avoimet',
  'comments.tab.resolved': 'Ratkaistut',
  'comments.add': 'Lisää kommentti',
  'comments.placeholder': 'Kirjoita kommentti',
  'comments.about': 'Koskee lohkoa: {block}',
  'comments.aboutIssue': 'Koskee koko kirjettä. Valitse lohko ensin, jos kommentti koskee sitä.',
  'comments.send': 'Kommentoi',
  'comments.resolve': 'Ratkaistu',
  'comments.reopen': 'Avaa uudelleen',
  'comments.delete': 'Poista',
  'comments.deleteConfirm': 'Poistetaanko kommentti?',
  'comments.resolvedBy': 'Ratkaisi {name} {when}',
  'comments.blockGone': 'Lohko on poistettu',
  'comments.none': 'Ei avoimia kommentteja.',
  'comments.noneResolved': 'Ei ratkaistuja kommentteja.',

  'test.title': 'Lähetä testiviesti',
  'test.to': 'Lähetä osoitteisiin',
  'test.toHint': 'Erota osoitteet pilkulla.',
  'test.note': 'Testi lähtee Mailchimpin kautta. Kirje viedään ensin Mailchimpiin luonnokseksi tai päivitetään siellä. Varsinainen lähetys tehdään aina Mailchimpissa.',
  'test.send': 'Lähetä testi',
  'test.sending': 'Viedään Mailchimpiin ja lähetetään…',
  'test.sent': 'Testi lähetetty: {to}',
  'test.noAddress': 'Kirjoita vähintään yksi osoite.',
  'test.notReady': 'Testi lähtee, kun Tarkistuksessa ei ole virheitä',
  'test.notReadyLead': 'Testi päivittää myös Mailchimpin luonnoksen, joten sitä koskee sama kuin vientiä. Korjaa nämä ensin. Esikatselu toimii aina.',

  'help.title': 'Näin käytät editoria',
  'help.add': 'Lisää sisältöä',
  'help.addText': 'Vedä lohko Lohkot-paneelista kirjeeseen. Violetti viiva näyttää, mihin se tulee. Lohkon voi myös napsauttaa, niin se tulee valitun kohdan alle.',
  'help.type': 'Kirjoita',
  'help.typeText': 'Napsauta tekstiä kirjeessä ja kirjoita. Muotoilut, linkit ja lukijan nimi löytyvät yläreunan työkaluriviltä.',
  'help.select': 'Muokkaa lohkoa',
  'help.selectText': 'Napsauta lohkoa: sen asetukset avautuvat vasemmalle. Lohkon oikealla puolella ovat siirrä, monista, kommentoi ja poista.',
  'help.move': 'Siirrä',
  'help.moveText': 'Vedä lohkoa sen nimilapusta tai siirrä-kuvakkeesta. Osioita voi järjestää Osiot-paneelissa.',
  'help.styles': 'Ulkoasu',
  'help.stylesText': 'Tyylit-paneelista vaihdat koko kirjeen fontit, värit ja painikkeet kerralla.',
  'help.check': 'Tarkista',
  'help.checkText': 'Tarkistus-paneeli kertoo, mitä vielä puuttuu: tarkistamattomat artikkelit, mallitekstit, kuvien kuvaukset ja linkit.',
  'help.save': 'Tallennus',
  'help.saveText': 'Editori tallentaa itse. Kumoa ja Tee uudelleen ovat yläreunassa, ja Esikatsele näyttää kirjeen tietokoneella ja puhelimessa.',
};

export const en = {
  'editor.title': 'Newsletter editor',
  'editor.toList': 'Newsletters',
  'editor.toIssue': 'Back to the newsletter',
  'editor.noIssue': 'Open the editor from a newsletter.',
  'editor.rename': 'Rename the newsletter',
  'editor.saved': 'Changes saved {when}',
  'editor.saving': 'Saving…',
  'editor.unsaved': 'Unsaved changes',
  'editor.saveFailed': "Couldn't save: {message}",
  'editor.loggedOut': 'Your login ended. Log in again in another tab and your changes will save.',
  'editor.sendTest': 'Send test',
  'editor.saveExit': 'Save and exit',
  'editor.moreSaving': 'More save options',
  'editor.saveAsTemplate': 'Save as template',
  'editor.changeTemplate': 'Change template',
  'editor.backWithoutChecks': 'Save and go back without checking',
  'editor.changeTemplateConfirm': 'A new template replaces what is in the email now. The picked articles are added to it again. Undo works once the template is chosen.',
  'editor.saveTemplateTitle': 'Save as template',
  'editor.saveTemplateHint': 'The template is saved without its articles. When it is used, that issue’s picked articles go into their sections.',
  'editor.templateSaved': 'Saved as a template: {name}',
  'editor.saveSectionTitle': 'Save section',
  'editor.saveSectionHint': 'Saved sections are under Sections → Saved, ready to add to any newsletter.',
  'editor.sectionSaved': 'Section saved: {name}',
  'editor.nameLabel': 'Name',
  'editor.newSection': 'New section',
  'editor.view': 'View',
  'editor.desktop': 'Desktop',
  'editor.mobile': 'Mobile',
  'editor.undo': 'Undo',
  'editor.redo': 'Redo',
  'editor.comments': 'Comments',
  'editor.preview': 'Preview',
  'editor.canvas': 'The newsletter',
  'editor.conflictTitle': 'Someone else saved in between',
  'editor.conflictText': '{name} saved the newsletter {when}, after you opened it. Which version stays?',
  'editor.conflictReload': 'Load their version',
  'editor.conflictOverwrite': 'Keep my version',
  'editor.exitErrors.one': 'We found 1 thing that needs your attention',
  'editor.exitErrors.other': 'We found {n} things that need your attention',
  'editor.exitErrorsLead': 'The newsletter is saved. These have to be fixed before it can go to Mailchimp:',
  'editor.exitAnyway': 'Save and exit',
  'editor.resolve': 'Fix them now',
  'editor.subjectTitle': 'Subject line and preview text',

  'rail.label': 'Panels',
  'rail.blocks': 'Blocks',
  'rail.sections': 'Sections',
  'rail.styles': 'Styles',
  'rail.check': 'Check',

  'block.text': 'Text',
  'block.image': 'Image',
  'block.button': 'Button',
  'block.divider': 'Divider',
  'block.spacer': 'Spacer',
  'block.social': 'Social',
  'block.video': 'Video',
  'block.logo': 'Logo',
  'block.footer': 'Footer',
  'block.columns': 'Columns',
  'block.article': 'Article',
  'block.link': 'Link',

  'tile.image': 'Image',
  'tile.heading': 'Heading',
  'tile.paragraph': 'Paragraph',
  'tile.button': 'Button',
  'tile.divider': 'Divider',
  'tile.spacer': 'Spacer',
  'tile.video': 'Video',
  'tile.social': 'Social',
  'tile.logo': 'Logo',
  'tile.footer': 'Footer',

  'blocks.help': 'How to use this editor',
  'blocks.title': 'Content blocks',
  'blocks.lead': 'Drag a block into the email, or click it to add it below what is selected.',
  'blocks.tileHint': '{name}: drag into the email or click',
  'blocks.articles': 'Picked articles',
  'blocks.articlesLead': 'Picked on the Articles page but not in the email yet. Click to put one in its section, or drag it where you want it.',
  'blocks.allPlaced': 'Every picked article is in the email.',
  'blocks.noneTicked': 'Pick articles on the Articles page and they appear here.',
  'blocks.articleHint': 'Click: into its section. Drag: wherever you like.',
  'blocks.addAll': 'Add all to their sections',
  'blocks.addedAll.one': '1 article added',
  'blocks.addedAll.other': '{n} articles added',
  'blocks.columnsTitle': 'Columns',
  'blocks.columnsLead': 'Drag a column layout into the email, then blocks into its columns.',
  'blocks.columnsHint': 'Columns {name}',
  'blocks.columns': 'Columns {layout}',
  'blocks.oneColumn': '1 column',

  'canvas.typeHere': 'Type here…',
  'canvas.addImage': 'Add an image: select this block and upload one on the left.',
  'canvas.addLogo': 'Add a logo',
  'canvas.addSocial': 'Add social links',
  'canvas.addVideo': 'Add the video address on the left.',
  'canvas.addArticleImage': 'Add a picture: select the article and add one on the left.',
  'canvas.dropHere': 'Drop a block here',
  'canvas.emptySection': 'Empty section. Drag blocks here.',
  'canvas.noArticles': 'No articles are picked for this section, so it is left out of the email.',
  'canvas.dragToMove': 'Drag to move',
  'canvas.move': 'Move',
  'canvas.duplicate': 'Duplicate',
  'canvas.comment': 'Comment',
  'canvas.delete': 'Delete',
  'canvas.markChecked': 'Mark as checked',
  'canvas.markUnchecked': 'Checked. Click to take the tick back.',
  'canvas.sectionUp': 'Move section up',
  'canvas.sectionDown': 'Move section down',
  'canvas.sectionMore': 'More actions',

  'tt.label': 'Text formatting',
  'tt.format': 'Text style',
  'tt.format.p': 'Paragraph',
  'tt.format.h1': 'Heading 1',
  'tt.format.h2': 'Heading 2',
  'tt.format.h3': 'Heading 3',
  'tt.format.h4': 'Heading 4',
  'tt.font': 'Font',
  'tt.fontDefault': 'Default font',
  'tt.size': 'Font size',
  'tt.sizeUp': 'Larger',
  'tt.sizeDown': 'Smaller',
  'tt.colour': 'Text colour',
  'tt.highlight': 'Highlight',
  'tt.noHighlight': 'No highlight',
  'tt.bold': 'Bold',
  'tt.italic': 'Italic',
  'tt.underline': 'Underline',
  'tt.strike': 'Strikethrough',
  'tt.link': 'Link',
  'tt.align': 'Alignment',
  'tt.alignLeft': 'Left',
  'tt.alignCenter': 'Centre',
  'tt.alignRight': 'Right',
  'tt.alignJustify': 'Justify',
  'tt.lineHeight': 'Line height',
  'tt.letterSpacing': 'Letter spacing',
  'tt.bullets': 'Bulleted list',
  'tt.numbers': 'Numbered list',
  'tt.more': 'More',
  'tt.clear': 'Clear formatting',
  'tt.titleNote': 'The headline takes its look from Styles (Heading 3). Type the headline here.',
  'tt.buttonNote': 'Type the button text. Colour, shape and size are on the left, under Styles.',

  'merge.fname': "Reader's first name",
  'merge.lname': "Reader's last name",
  'merge.email': "Reader's email address",
  'merge.date': "Today's date",
  'merge.year': 'This year',
  'merge.company': "The association's name",
  'merge.unsub': 'Unsubscribe link',
  'merge.profile': 'Update profile link',
  'merge.archive': 'View in browser link',

  'link.title': 'Link',
  'link.to': 'Link to',
  'link.kind': 'Link type',
  'link.kind.web': 'Web page',
  'link.kind.email': 'Email',
  'link.kind.phone': 'Phone',
  'link.placeholder.web': 'https://',
  'link.placeholder.email': 'name@example.com',
  'link.placeholder.phone': '+358 40 123 4567',
  'link.address': 'Address',
  'link.newTab': 'Open in a new tab',
  'link.save': 'Save',
  'link.remove': 'Remove link',

  'control.more': 'More',
  'control.less': 'Less',
  'control.colourCode': 'Colour code',
  'control.pickColour': 'Pick a colour',
  'control.noColour': 'No colour',
  'control.allSides': 'All sides',
  'control.sameAllSides': 'Same on all sides',
  'control.top': 'Top',
  'control.bottom': 'Bottom',
  'control.left': 'Left',
  'control.right': 'Right',

  'align.left': 'Left',
  'align.center': 'Centre',
  'align.right': 'Right',
  'border.none': 'No border',
  'border.solid': 'Solid',
  'border.dashed': 'Dashed',
  'border.dotted': 'Dotted',

  'settings.back': 'Back',
  'settings.tab.content': 'Content',
  'settings.tab.styles': 'Styles',
  'settings.section': 'Section',
  'settings.blockBackground': 'Block background',
  'settings.border': 'Border',
  'settings.borderStyle': 'Border style',
  'settings.borderWidth': 'Width',
  'settings.borderColour': 'Border colour',
  'settings.radius': 'Rounded corners',
  'settings.padding': 'Padding',
  'settings.margin': 'Margin',
  'settings.align': 'Alignment',
  'settings.noImage': 'Drop an image here or choose one',
  'settings.upload': 'Upload',
  'settings.library': 'Image library',
  'settings.replace': 'Replace',
  'settings.removeImage': 'Remove image',
  'settings.size': 'Size',
  'settings.sizeOriginal': 'Original',
  'settings.sizeFill': 'Fill',
  'settings.sizeScale': 'Scale',
  'settings.scale': 'Width',
  'settings.link': 'Link',
  'settings.alt': 'Alt text',
  'settings.altPlaceholder': 'Say what the image shows',
  'settings.altHint': 'Shown when the image does not load, and read out by screen readers.',
  'settings.logoWidth': 'Width',
  'settings.buttonText': 'Button text',
  'settings.shape': 'Shape',
  'settings.square': 'Square',
  'settings.round': 'Round',
  'settings.pill': 'Pill',
  'settings.buttonColour': 'Button colour',
  'settings.textColour': 'Text colour',
  'settings.linkColour': 'Link colour',
  'settings.font': 'Font',
  'settings.fontSize': 'Font size',
  'settings.bold': 'Bold',
  'settings.italic': 'Italic',
  'settings.letterSpacing': 'Letter spacing',
  'settings.buttonSize': 'Button size',
  'settings.small': 'Small',
  'settings.medium': 'Medium',
  'settings.large': 'Large',
  'settings.fullWidth': 'Full width',
  'settings.lineStyle': 'Line style',
  'settings.lineColour': 'Line colour',
  'settings.thickness': 'Thickness',
  'settings.height': 'Height',
  'settings.network': 'Service',
  'settings.up': 'Up',
  'settings.remove': 'Remove',
  'settings.socialLabel': 'Label',
  'settings.addSocial': 'Add a link',
  'settings.display': 'Display',
  'settings.displayIcon': 'Icon',
  'settings.displayBoth': 'Icon and text',
  'settings.displayText': 'Text',
  'settings.iconStyle': 'Icon style',
  'settings.iconColour': 'Colour',
  'settings.iconDark': 'Dark',
  'settings.iconLight': 'Light',
  'settings.layout': 'Layout',
  'settings.horizontal': 'Horizontal',
  'settings.vertical': 'Vertical',
  'settings.iconSize': 'Size',
  'settings.spacing': 'Spacing',
  'settings.videoUrl': 'Video address',
  'settings.videoHint': 'A YouTube or Vimeo video. The preview image is fetched by itself, and clicking it opens the video.',
  'settings.videoFetching': 'Fetching the preview image…',
  'settings.thumbnail': 'Preview image',
  'settings.columnCount': 'Number of columns',
  'settings.columnLayout': 'Column widths',
  'settings.equal': 'Equal',
  'settings.mobile': 'On phones',
  'settings.stack': 'Stack',
  'settings.stackReverse': 'Stack, reversed',
  'settings.sideBySide': 'Side by side',
  'settings.valign': 'Vertical alignment',
  'settings.top': 'Top',
  'settings.middle': 'Middle',
  'settings.bottom': 'Bottom',
  'settings.columnBackground': 'Column background',
  'settings.checked': 'Checked',
  'settings.checkedHint': 'Tick this once you have read the text the AI wrote and corrected it where needed. Unchecked text has an orange dashed outline in the email.',
  'settings.original': 'Original article',
  'settings.foreignTitle': 'The headline is still in its original language ({lang}). Translate it so the whole email is in Finnish.',
  'settings.title': 'Headline',
  'settings.linkTitle': 'Headline links to the article',
  'settings.showSource': 'Show the source line',
  'settings.articleButton': 'Button',
  'settings.showButton': 'Show a button',
  'settings.articleLayout': 'Layout',
  'settings.layoutText': 'Text',
  'settings.layoutLeft': 'Image left',
  'settings.layoutRight': 'Image right',
  'settings.layoutTop': 'Image on top',
  'settings.articleLook': 'How articles look',
  'settings.articleLookHint': 'Applies to every article in this section.',
  'settings.lookPlain': 'Plain',
  'settings.lookLarge': 'Large title',
  'settings.lookCard': 'Card',
  'settings.lookBar': 'Title bar',
  'settings.cardColour': 'Card colour',
  'settings.barColour': 'Bar colour',
  'settings.lookDefaultColour': 'Default',
  'settings.newArticleLayout': 'Layout for new articles',
  'settings.newArticleLayoutHint': "Applies to articles that come into this section from now on. One article's layout can be changed in its own settings.",
  'settings.anchor': 'Link to this section',
  'settings.spaceAbove': 'Space above',
  'settings.spaceAboveHint': 'White space before the section, so coloured sections stand apart.',
  'settings.anchorHint': "A short name, like events. A link to #events takes the reader to this section, if their email program allows it.",
  'settings.articleImage': 'Article image',
  'settings.imageRights': "Use only images the association has the right to use. Don't copy the publisher's image without permission.",
  'settings.moveTo': 'Section',
  'settings.footerNote': 'The footer needs a link that lets readers unsubscribe. Mailchimp requires it and will not send without it.',
  'settings.footerHasUnsub': 'The unsubscribe link is there.',
  'settings.footerNoUnsub': 'The unsubscribe link is missing.',
  'settings.addUnsub': 'Add an unsubscribe link',
  'settings.footerHasAddress': 'The postal address is there.',
  'settings.footerNoAddress': 'The postal address is missing. Mailchimp requires it.',
  'settings.addAddress': 'Add the postal address',
  'settings.resetFooter': 'Restore the default text',
  'settings.clearStyles': 'Clear styles',
  'settings.applyAll': 'Apply to all',
  'settings.appliedAll': 'Styles applied to every {type} block',
  'settings.sectionName': 'Section name',
  'settings.sectionBackground': 'Section background',
  'settings.sectionBackgroundHint': 'A colour across the full width, beside the content too.',
  'settings.contentBackground': 'Content background',
  'settings.sectionText': 'Text',
  'settings.sectionLink': 'Links',
  'settings.samePage': 'Same as the page background',
  'settings.sameEmail': "Same as the email's styles",
  'settings.saveSection': 'Save section',
  'settings.duplicateSection': 'Duplicate',
  'settings.deleteSection': 'Delete section',

  'sections.title': 'Sections',
  'sections.lead': 'The email is made of sections. Put them in order, add ready-made ones, or use ones you saved.',
  'sections.tab.manage': 'Manage',
  'sections.tab.prebuilt': 'Ready-made',
  'sections.tab.trends': 'Trends',
  'sections.trendsLead': 'Signals found on {date}: topics the sources wrote about again and again. Drag one into the email, or press it to put it after Nostoja kentältä. The box lists a few of its articles, and you write why the topic matters now.',
  'sections.trendsNone': 'No signals yet, or no topic came up more than once. They are looked for every Monday, and on Artikkelit you can look now.',
  'sections.trendsCount.one': '{n} article',
  'sections.trendsCount.other': '{n} articles',
  'sections.tab.saved': 'Saved',
  'sections.drag': 'Drag to reorder',
  'sections.up': 'Up',
  'sections.down': 'Down',
  'sections.more': 'More actions: {name}',
  'sections.notSent': 'not in the email',
  'sections.rename': 'Rename',
  'sections.duplicate': 'Duplicate',
  'sections.save': 'Save section',
  'sections.delete': 'Delete',
  'sections.addBlank': 'Add a blank section',
  'sections.addHint': 'Drag into the email or click',
  'sections.group.header': 'Header',
  'sections.group.hero': 'Introduction',
  'sections.group.articles': 'Articles',
  'sections.group.text': 'Text and button',
  'sections.group.gallery': 'Images',
  'sections.group.signup': 'Joining and subscribing',
  'sections.group.event': 'Event',
  'sections.group.columns': 'Highlights in columns',
  'sections.group.footer': 'Footer',
  'sections.loading': 'Loading…',
  'sections.search': 'Search by name',
  'sections.noSaved': 'No saved sections yet. Select a section in the email and choose Save section.',
  'sections.savedMore': 'More actions',
  'sections.renameSaved': 'Rename saved section',
  'sections.deleteSavedConfirm': 'Delete the saved section {name}? Sections already in emails stay as they are.',

  'styles.title': 'Email styles',
  'styles.lead': 'The look of the whole email. A single block or section can change its own in its settings.',
  'styles.background': 'Background',
  'styles.text': 'Text',
  'styles.link': 'Links',
  'styles.button': 'Buttons',
  'styles.divider': 'Dividers',
  'styles.image': 'Images',
  'styles.logo': 'Logo',
  'styles.contentColour': 'Content colour',
  'styles.pageColour': 'Background colour',
  'styles.margin': 'Space above and below',
  'styles.marginHint': 'How much background shows above and below the email.',
  'styles.mobilePadding': 'Side padding on phones',
  'styles.mobilePaddingHint': 'On phones, text keeps this much space from the edges.',
  'styles.textKind': 'Kind of text',
  'styles.font': 'Font',
  'styles.letterSpacing': 'Letter spacing',
  'styles.textColour': 'Text colour',
  'styles.size': 'Size',
  'styles.mobileSize': 'Size on phones',
  'styles.lineHeight': 'Line height',
  'styles.spacing': 'Paragraph spacing',
  'styles.linkColour': 'Link colour',
  'styles.underline': 'Underline links',

  'check.title': 'Check',
  'check.lead': 'Errors have to be fixed before the email can go to Mailchimp or out as a test. Warnings are worth a look.',
  'check.errorCount.one': '1 error',
  'check.errorCount.other': '{n} errors',
  'check.warningCount.one': '1 warning',
  'check.warningCount.other': '{n} warnings',
  'check.allGood': 'All good.',
  'check.show': 'Show',
  'check.open': 'Open',
  'check.markChecked': 'Mark as checked',
  'check.markAll': 'Mark all as checked',
  'check.markAllConfirm': 'Have you read all {n} articles? The tick says a person has checked the AI’s text.',
  'check.insert': 'Add to the email',
  'check.insertAll': 'Add all to their sections',
  'check.removeFromEmail': 'Remove from the email',
  'check.addUnsub': 'Add an unsubscribe link',
  'check.addSubject': 'Write a subject line',
  'check.noAddress': 'no address',
  'check.links': 'Links',
  'check.mergeTags': 'Merge tags',
  'check.mergeTagsHint': 'Mailchimp fills these in for each reader when it sends. The preview shows them as they are.',
  'check.unchecked.one': '1 article not checked',
  'check.unchecked.other': '{n} articles not checked',
  'check.uncheckedHint': 'Read the text the AI wrote and mark the article checked. The tick says a person has read it.',
  'check.uncheckedDraft.one': '1 AI draft not checked',
  'check.uncheckedDraft.other': '{n} AI drafts not checked',
  'check.uncheckedDraftHint': 'Read the draft the AI wrote, correct it where needed and mark it checked.',
  'check.placeholders.one': '1 piece of placeholder text',
  'check.placeholders.other': '{n} pieces of placeholder text',
  'check.placeholdersHint': 'Replace or remove sample text such as "Type here…" or "Button text". The email goes to Mailchimp only once none is left.',
  'check.unsubscribe.one': 'No unsubscribe link',
  'check.unsubscribe.other': 'No unsubscribe link',
  'check.unsubscribeHint': 'Every email needs a link that lets readers unsubscribe. Mailchimp requires it.',
  'check.address.one': 'No postal address',
  'check.address.other': 'No postal address',
  'check.addressHint': "Mailchimp requires the sender's postal address in every email. The tag *|LIST:ADDRESSLINE|* fills it in from the audience's settings in Mailchimp.",
  'check.addAddress': 'Add the address to the footer',
  'check.subject.one': 'No subject line',
  'check.subject.other': 'No subject line',
  'check.subjectHint': "The subject line is the email's title in the reader's inbox.",
  'check.foreign.one': '1 headline in its original language',
  'check.foreign.other': '{n} headlines in their original language',
  'check.foreignHint': 'The headline is still as the publisher wrote it. Translate it if the rest of the email is in Finnish.',
  'check.missing.one': '1 picked article is not in the email',
  'check.missing.other': '{n} picked articles are not in the email',
  'check.missingHint': 'Picked on the Articles page but not in the email yet.',
  'check.orphans.one': '1 article is no longer picked',
  'check.orphans.other': '{n} articles are no longer picked',
  'check.orphansHint': 'These were unpicked on the Articles page but are still in the email.',
  'check.alt.one': '1 image without alt text',
  'check.alt.other': '{n} images without alt text',
  'check.altHint': 'Say briefly what the image shows. The text appears when the image does not load, and screen readers read it.',
  'check.emptyImages.one': '1 picture spot without a picture',
  'check.emptyImages.other': '{n} picture spots without a picture',
  'check.emptyImagesHint': "The preview shows a grey box there. The email that goes out leaves them out: an image block entirely, an article as text only. Add a picture, delete the block or set the article's layout to Text.",
  'check.emptyLinks.one': '1 link without an address',
  'check.emptyLinks.other': '{n} links without an address',
  'check.emptyLinksHint': 'A link or button with no address takes the reader nowhere.',
  'check.size.one': 'The email is {kb} KB: Gmail will clip it',
  'check.size.other': 'The email is {kb} KB: Gmail will clip it',
  'check.sizeHint': 'Gmail shows only 102 KB and hides the rest, unsubscribe link included. Shorten the email.',

  'linkKind.text': 'Text link',
  'linkKind.button': 'Button',
  'linkKind.image': 'Image link',
  'linkKind.video': 'Video',
  'linkKind.social': 'Social link',
  'linkKind.title': 'Headline link',

  'dialog.close': 'Close',
  'dialog.cancel': 'Cancel',
  'dialog.ok': 'OK',
  'dialog.save': 'Save',
  'dialog.confirm': 'Are you sure?',

  'library.title': 'Image library',
  'library.scope.all': 'All images',
  'library.scope.issue': "This email's images",
  'library.search': 'Search by name',
  'library.upload': 'Upload images',
  'library.dropHint': "You can also drop images on this window. They are shrunk to suit email, and the camera's data, such as where a photo was taken, is removed.",
  'library.loading': 'Loading…',
  'library.uploading': 'Uploading…',
  'library.uploaded.one': '1 image uploaded',
  'library.uploaded.other': '{n} images uploaded',
  'library.uploadFailed': "Couldn't upload the image.",
  'library.empty': 'No images yet',
  'library.nothingFound': 'Nothing found',
  'library.emptyHint': 'Upload images from your computer and they are ready for every newsletter.',
  'library.pick': 'Use this image',
  'library.delete': 'Delete image',
  'library.deleteConfirm': 'Delete the image {name}? It also disappears from sent emails that used it.',
  'library.deleted': 'Image deleted',
  'library.showing': 'Showing {from}–{to} of {total}',
  'library.page': 'Page {page} of {pages}',
  'library.previous': 'Previous',
  'library.next': 'Next',

  'preview.title': 'Preview',
  'preview.frameTitle': 'The email as readers see it',
  'preview.sendTest': 'Send a test',
  'preview.pictureHere': 'Picture goes here',
  'preview.videoHere': 'Video goes here',
  'preview.logoHere': 'Logo',
  'preview.info': 'Email info',
  'preview.from': 'From',
  'preview.fromMailchimp': 'Set in Mailchimp',
  'preview.subject': 'Subject',
  'preview.preheader': 'Preview text',
  'preview.noSubject': 'No subject line',
  'preview.noPreheader': 'No preview text',
  'preview.checkLinks': 'Check links ({checked}/{total})',
  'preview.linksChecked': '{checked} of {total} links checked',
  'preview.linksHint': 'Open each link and see that it goes to the right place.',
  'preview.noLinks': 'The email has no links.',
  'preview.linkDetails': 'Link details',
  'preview.openLink': 'Open link',
  'preview.markChecked': 'Mark as checked',
  'preview.editLink': 'Edit',
  'preview.linkOf': 'Link {n} of {total}',
  'preview.mergeLink': "Mailchimp turns this into each reader's own link when it sends.",
  'preview.emptyLink': 'This link has no address.',
  'preview.size': 'Email size',
  'preview.clipped': 'Gmail clips emails over 102 KB. Shorten the email.',
  'preview.notClipped': 'Gmail shows the whole email.',

  'chooser.title': 'Choose a template',
  'chooser.lead': 'The email starts from a template. The picked articles go into their sections, and everything can be changed later.',
  'chooser.back': 'Back',
  'chooser.tab.builtin': 'Ready-made',
  'chooser.tab.saved': 'Saved',
  'chooser.tab.past': 'Earlier newsletters',
  'chooser.use': 'Use this',
  'chooser.preview': 'Preview',
  'chooser.recommended': 'Recommended',
  'chooser.loading': 'Loading…',
  'chooser.noSaved': 'No saved templates yet. In the editor: Save and exit ▾ → Save as template.',
  'chooser.noPast': 'No earlier newsletters yet.',
  'chooser.pastLead': "The same look and texts, with this issue's articles.",
  'chooser.sentOn': 'Sent {date}',
  'chooser.draft': 'Draft',

  'template.eok': "The association's newsletter",
  'template.eok.lead': 'Like the newsletter sent from Mailchimp today: the banner, own news with pictures, events and highlights in pink boxes, tips, Learning Factory and joining.',
  'template.jasenkirje': 'Member letter',
  'template.jasenkirje.lead': 'Like the member letter: a list of contents, a large picture, the picks to read first, sections under magenta bars and headlines in green bars.',
  'template.simple': 'Simple',
  'template.simple.lead': 'White and clear, few colours. Good for a short email.',
  'template.visual': 'Visual',
  'template.visual.lead': 'A logo, a large main image and an introduction in two columns.',
  'template.blank': 'Start from scratch',
  'template.blank.lead': 'A header, an empty content section and a footer. Build the rest from blocks.',
  'chooser.all': 'All',
  'chooser.filter': 'Show templates',
  'chooser.group.newsletters': 'Newsletters',
  'chooser.group.events': 'Events',
  'chooser.group.announcements': 'Announcements and surveys',
  'chooser.group.membership': 'Membership',
  'chooser.group.training': 'Training',
  'chooser.group.greetings': 'Greetings',
  'chooser.group.layouts': 'Basic layouts',
  'template.letter': 'Letter to members',
  'template.letter.lead': 'A personal letter: the banner, the text and a signature with a photo.',
  'template.join': 'Join us',
  'template.join.lead': 'Invite people to join: why, three member benefits and a button to the membership page.',
  'template.event': 'Event invitation',
  'template.event.lead': 'A main image, the event details, the programme, speakers and a sign-up button.',
  'template.webinar': 'Webinar invitation',
  'template.webinar.lead': 'When it is, what participants learn, the speaker and signing up.',
  'template.reminder': 'Reminder',
  'template.reminder.lead': 'A short reminder just before an event: time, place and a button to join.',
  'template.thanks': 'Thank you for joining',
  'template.thanks.lead': 'After an event: the recording, materials, photos and a feedback survey.',
  'template.announce': 'Announcement',
  'template.announce.lead': 'One important thing: a large image, a headline, text and a button.',
  'template.meeting': 'Meeting invitation',
  'template.meeting.lead': "An invitation to the association's meeting: time, place, agenda and signing up.",
  'template.survey': 'Survey',
  'template.survey.lead': 'Ask members for feedback or their opinion with one clear button.',
  'template.course': 'Training offer',
  'template.course.lead': "An introduction, three courses side by side, a participant's feedback and a button.",
  'template.training': 'Training course',
  'template.training.lead': 'One course in detail: the facts, contents, trainer and signing up.',
  'template.welcome': 'Welcome, new member',
  'template.welcome.lead': 'For a new member: member benefits, first steps and a contact person.',
  'template.greeting': 'Holiday greeting',
  'template.greeting.lead': 'A picture and a few warm words, centred. For Christmas and other occasions.',
  'template.onecol': 'One column',
  'template.onecol.lead': 'Logo, image, text and button one after another. Easy to adapt to anything.',
  'template.twocol': 'Two columns',
  'template.twocol.lead': 'Four highlights in two columns, each with an image, text and a button.',
  'template.threecol': 'Three columns',
  'template.threecol.lead': 'Three short highlights side by side, with images.',
  'template.zigzag': 'Alternating image and text',
  'template.zigzag.lead': 'Image and text side by side, swapping sides on every row.',
  'template.plain': 'Plain text',
  'template.plain.lead': 'Like an ordinary email: no colours and no images.',

  'comments.title': 'Comments',
  'comments.tab.open': 'Open',
  'comments.tab.resolved': 'Resolved',
  'comments.add': 'Add a comment',
  'comments.placeholder': 'Write a comment',
  'comments.about': 'About the block: {block}',
  'comments.aboutIssue': 'About the whole email. Select a block first if the comment is about it.',
  'comments.send': 'Comment',
  'comments.resolve': 'Resolve',
  'comments.reopen': 'Reopen',
  'comments.delete': 'Delete',
  'comments.deleteConfirm': 'Delete this comment?',
  'comments.resolvedBy': 'Resolved by {name} {when}',
  'comments.blockGone': 'The block was deleted',
  'comments.none': 'No open comments.',
  'comments.noneResolved': 'No resolved comments.',

  'test.title': 'Send a test email',
  'test.to': 'Send to',
  'test.toHint': 'Separate addresses with commas.',
  'test.note': 'The test goes through Mailchimp. The email is first exported to Mailchimp as a draft, or updated there. The real send always happens in Mailchimp.',
  'test.send': 'Send test',
  'test.sending': 'Exporting to Mailchimp and sending…',
  'test.sent': 'Test sent: {to}',
  'test.noAddress': 'Type at least one address.',
  'test.notReady': 'The test can go once Check lists no errors',
  'test.notReadyLead': 'A test also updates the draft in Mailchimp, so the same rule applies as for exporting. Fix these first. The preview works any time.',

  'help.title': 'How to use this editor',
  'help.add': 'Add content',
  'help.addText': 'Drag a block from the Blocks panel into the email. A purple line shows where it lands. You can also click a block to add it below what is selected.',
  'help.type': 'Type',
  'help.typeText': "Click text in the email and type. Formatting, links and the reader's name are in the toolbar at the top.",
  'help.select': 'Change a block',
  'help.selectText': 'Click a block and its settings open on the left. To its right are move, duplicate, comment and delete.',
  'help.move': 'Move',
  'help.moveText': 'Drag a block by its label or its move icon. Sections are put in order in the Sections panel.',
  'help.styles': 'Look',
  'help.stylesText': "The Styles panel changes the whole email's fonts, colours and buttons at once.",
  'help.check': 'Check',
  'help.checkText': 'The Check panel says what is still missing: unchecked articles, sample text, image descriptions and links.',
  'help.save': 'Saving',
  'help.saveText': 'The editor saves by itself. Undo and Redo are at the top, and Preview shows the email on a computer and a phone.',
};
