// The words of the newsletter pages: the list of newsletters, one
// newsletter's checklist, the way into Mailchimp and the admins' settings.
// texts.js adds them to the dashboard's own.

export const fi = {
  'nav.newsletters': 'Uutiskirjeet',
  'nav.settings': 'Asetukset',

  'list.title': 'Uutiskirjeet',
  'list.lead': 'Kaikki uutiskirjeet, luonnokset ensin. Kirje tehdään täällä ja lähetetään Mailchimpista.',
  'list.create': 'Luo uutiskirje',
  'list.createTitle': 'Luo uutiskirje',
  'list.createButton': 'Luo ja avaa editori',
  'list.nameLabel': 'Nimi',
  'list.nameHint': 'Vain te näette nimen. Jätä tyhjäksi, niin kirje nimetään kuukauden mukaan. Uudet valinnat menevät tähän kirjeeseen.',
  'list.search': 'Hae nimellä tai aiheella',
  'list.filter': 'Näytä',
  'list.filter.all': 'Kaikki',
  'list.filter.draft': 'Luonnokset',
  'list.filter.sent': 'Lähetetyt',
  'list.col.name': 'Nimi',
  'list.col.edited': 'Muokattu',
  'list.col.status': 'Tila',
  'list.col.mailchimp': 'Mailchimp',
  'list.col.actions': 'Toiminnot',
  'list.status.draft': 'Luonnos',
  'list.status.sent': 'Lähetetty',
  'list.subject': 'Aihe: {subject}',
  'list.noSubject': 'Ei aiheriviä',
  'list.articles.one': '1 artikkeli',
  'list.articles.other': '{n} artikkelia',
  'list.comments.one': '1 avoin kommentti',
  'list.comments.other': '{n} avointa kommenttia',
  'list.current': 'Uudet valinnat tulevat tähän',
  'list.edit': 'Muokkaa',
  'list.open': 'Avaa',
  'list.editContent': 'Muokkaa sisältöä',
  'list.preview': 'Esikatsele',
  'list.rename': 'Nimeä uudelleen',
  'list.replicate': 'Käytä pohjana',
  'list.replicateTitle': 'Uusi kirje tämän pohjalta',
  'list.replicateHint': 'Uusi kirje saa saman ulkoasun ja tekstit, ja siihen tulevat uudet valitut artikkelit. Jätä nimi tyhjäksi, niin kirje nimetään kuukauden mukaan.',
  'list.delete': 'Poista',
  'list.deleteConfirm': 'Poistetaanko luonnos {name}? Sen {n} valittua artikkelia palaavat Artikkelit-sivulle valitsemattomiksi.',
  'list.deleted': 'Poistettu: {name}',
  'list.more': 'Lisää toimintoja: {name}',
  'list.nothing': 'Ei osumia.',
  'list.emptyTitle': 'Ei vielä uutiskirjeitä',
  'list.emptyLead': 'Kirje syntyy itsestään, kun valitset ensimmäisen artikkelin Artikkelit-sivulla. Voit myös luoda sen tästä.',
  'list.manyDrafts': 'Luonnoksia on useampi. Artikkelit-sivulla valitut artikkelit menevät uusimpaan, jossa lukee "Uudet valinnat tulevat tähän".',
  'list.mcNone': 'Ei viety',
  'list.mcDraft': 'Luonnos Mailchimpissa, viety {when}',
  'list.mcScheduled': 'Ajastettu Mailchimpissa',
  'list.mcSent': 'Lähetetty Mailchimpista',
  'list.mcMarked': 'Merkitty lähetetyksi',
  'list.mcDeleted': 'Poistettu Mailchimpista',

  'issue.toList': 'Uutiskirjeet',
  'issue.back': 'Takaisin',
  'issue.finishLater': 'Viimeistele myöhemmin',
  'issue.export': 'Vie Mailchimpiin',
  'issue.rename': 'Nimeä uudelleen',
  'issue.progress': '{done}/{total} valmiina',
  'issue.sentNote': 'Lähetetty {date}. Kirjettä ei voi enää muuttaa, mutta sitä voi käyttää uuden pohjana.',
  'issue.lineArticles': 'Artikkelit',
  'issue.lineSubject': 'Aihe',
  'issue.lineContent': 'Sisältö',
  'issue.lineMailchimp': 'Mailchimp',
  'issue.articleCount.one': '1 artikkeli valittu',
  'issue.articleCount.other': '{n} artikkelia valittu',
  'issue.noArticles': 'Ei vielä valittuja artikkeleita. Valitse niitä Artikkelit-sivulla.',
  'issue.pickMore': 'Valitse artikkeleita',
  'issue.show': 'Näytä',
  'issue.hide': 'Piilota',
  'issue.unpickConfirm': 'Poistetaanko artikkeli tästä kirjeestä? Se palaa Artikkelit-sivulle valitsemattomaksi.',
  'issue.subjectQuestion': 'Mikä on kirjeen aiherivi?',
  'issue.addSubject': 'Lisää aiherivi',
  'issue.edit': 'Muokkaa',
  'issue.preheaderShown': 'Esikatseluteksti: {text}',
  'issue.noPreheader': 'Ei esikatselutekstiä.',
  'issue.design': 'Suunnittele kirje',
  'issue.notDesigned': 'Kirjettä ei ole vielä avattu editorissa. Editori kokoaa sen valituista artikkeleista.',
  'issue.editContent': 'Muokkaa sisältöä',
  'issue.mailchimpHow': 'Kun sisältö on valmis, vie kirje Mailchimpiin. Siellä valitaan vastaanottajat ja kirje lähetetään.',
  'issue.recipients': '{n} vastaanottajaa',
  'issue.openPreview': 'Avaa omaan välilehteen',

  'handoff.title': 'Vie Mailchimpiin',
  'handoff.lead': 'Kirje siirretään Mailchimpiin, ja lähetät sen sieltä. Valitse tapa. Suosittelemme ylintä.',
  'handoff.recommended': 'Suositeltu',
  'handoff.plan.standard': 'Mailchimp-paketti: Standard tai Premium.',
  'handoff.plan.essentials': 'Mailchimp-paketti: Essentials.',
  'handoff.plan.unknown': 'Mailchimp-pakettia ei ole kerrottu asetuksissa. Essentials-paketissa vain kopiointi toimii.',
  'handoff.draftTitle': 'Luonnos suoraan Mailchimpiin',
  'handoff.draftLead': 'Yksi painallus, ja kirje, sen kuvat, aiherivi ja esikatseluteksti ovat Mailchimpissa valmiina luonnoksena.',
  'handoff.essentialsWarning': 'Essentials-paketissa Mailchimp ei lähetä muualla tehtyä kirjettä, vaan pyytää päivittämään Standard-pakettiin. Käytä silloin kopiointia omaan pohjaanne.',
  'handoff.connectedTo': 'Yhdistetty Mailchimp-tiliin {name}.',
  'handoff.notConnected': 'Mailchimpia ei ole yhdistetty. Ylläpitäjä yhdistää sen Asetukset-sivulla.',
  'handoff.draftStep1': 'Paina "Luo luonnos Mailchimpiin".',
  'handoff.draftStep2': 'Avaa luonnos Mailchimpissa. Se on Campaigns-listalla tämän kirjeen nimellä.',
  'handoff.draftStep3': 'Valitse Mailchimpissa vastaanottajat, lähetä testi itsellesi ja lähetä tai ajasta kirje.',
  'handoff.createDraft': 'Luo luonnos Mailchimpiin',
  'handoff.updateDraft': 'Päivitä luonnos Mailchimpissa',
  'handoff.updateConfirm': 'Päivitys korvaa Mailchimpin luonnoksen sisällön tämän kirjeen sisällöllä. Mailchimpissa tehdyt muutokset sisältöön katoavat. Jatketaanko?',
  'handoff.exporting': 'Viedään…',
  'handoff.exported': 'Viety Mailchimpiin {when} ({name}).',
  'handoff.exportedToast': 'Luonnos on nyt Mailchimpissa.',
  'handoff.changedSince': 'Kirjettä on muutettu viennin jälkeen. Päivitä luonnos Mailchimpissa.',
  'handoff.openInMailchimp': 'Avaa Mailchimpissa',
  'handoff.copyTitle': 'Kopioi omaan Mailchimp-pohjaanne',
  'handoff.copyLead': 'Toimii kaikissa Mailchimp-paketeissa. Kirje kootaan Mailchimpin omassa editorissa tavallisesta pohjastanne.',
  'handoff.copyStep1': 'Avaa Mailchimpissa uusi sähköposti tavallisesta pohjastanne, tai monista edellinen uutiskirje (Campaigns → ▾ → Replicate).',
  'handoff.copyStep2': 'Paina osion kohdalla "Kopioi", napsauta Mailchimpissa tekstilohkoa ja liitä (Cmd+V, Windowsissa Ctrl+V).',
  'handoff.copyStep3': 'Kopioi lopuksi aiherivi ja esikatseluteksti Mailchimpin Subject-kohtaan.',
  'handoff.picturesCopied': 'Kuvat siirretään Mailchimpiin, kun kopioit osion, joten ne näkyvät lukijoille.',
  'handoff.picturesLocal': 'Dashboard ei ole vielä internetissä, joten kuvat eivät näy Mailchimpissa. Lisää kuvat Mailchimpissa, tai yhdistä Mailchimp, niin kuvat siirtyvät sinne.',
  'handoff.copy': 'Kopioi',
  'handoff.copied': 'Kopioitu',
  'handoff.copiedSection': 'Kopioitu: {name}. Liitä se Mailchimpiin.',
  'handoff.copiedThing': 'Kopioitu: {what}',
  'handoff.copyFailed': 'Kopiointi ei onnistunut tässä selaimessa.',
  'handoff.subject': 'aiherivi',
  'handoff.preheader': 'esikatseluteksti',
  'handoff.copySubject': 'Kopioi aiherivi',
  'handoff.copyPreheader': 'Kopioi esikatseluteksti',
  'handoff.codeTitle': 'Vaihtoehto: koko kirje kerralla Mailchimpin Code-lohkoon',
  'handoff.codeLead': 'Mailchimpin omassa editorissa on Code-lohko, johon voi liittää koko kirjeen kerralla. Lisää tyhjään sähköpostiin Code-lohko ja liitä tämä siihen. Testaa ensin, sallitaanko se teidän paketissanne.',
  'handoff.copyCode': 'Kopioi koko kirje koodina',
  'handoff.wholeEmail': 'koko kirje',
  'handoff.fileTitle': 'Tiedostona',
  'handoff.fileLead': 'Lataa kirje tiedostona ja tuo se Mailchimpiin pohjaksi. Kuvat kulkevat tiedoston mukana.',
  'handoff.fileStep1': 'Lataa ZIP-tiedosto.',
  'handoff.fileStep2': 'Mailchimpissa: Campaigns → Email templates → Code your own ▾ → Import ZIP, ja valitse tiedosto.',
  'handoff.fileStep3': 'Tallenna pohja (Save and Exit).',
  'handoff.fileStep4': 'Luo pohjasta sähköposti: Saved-välilehti → pohja → Create email. Valitse vastaanottajat ja lähetä.',
  'handoff.downloadZip': 'Lataa ZIP',
  'handoff.downloadHtml': 'Lataa HTML',
  'handoff.copyHtml': 'Kopioi HTML',
  'handoff.zipTooBig': 'Tiedosto on {kb} kt. Mailchimp ottaa vastaan alle 1 Mt tiedostoja: pienennä kuvia tai poista niitä.',
  'handoff.afterSending': 'Lähetitkö kirjeen Mailchimpista toisella tavalla kuin luonnoksena? Merkitse se lähetetyksi, niin sen artikkelit merkitään käytetyiksi.',

  'admin.title': 'Asetukset',
  'admin.lead': 'Mailchimp-yhteys ja se, miten luonnokset tehdään Mailchimpiin.',
  'admin.mailchimp': 'Mailchimp',
  'admin.test': 'Testaa yhteys',
  'admin.testing': 'Testataan…',
  'admin.testOk': 'Yhteys toimii.',
  'admin.testBad': 'Yhteys ei toimi. Katso syy sivulta.',
  'admin.connected': 'Yhdistetty Mailchimp-tiliin {name}.',
  'admin.audienceLine': 'Yleisö: {name}, {n} tilaajaa',
  'admin.notConnectedTitle': 'Ei yhdistetty.',
  'admin.notConnected': 'n8n ei saanut yhteyttä Mailchimpiin.',
  'admin.server': 'Mailchimpin datakeskus',
  'admin.serverHint': 'Näkyy Mailchimpin osoitteessa, kun olet kirjautunut: us4.admin.mailchimp.com → us4. Se on myös API-avaimen loppuosa.',
  'admin.audience': 'Yleisö',
  'admin.audienceNone': 'Valitaan Mailchimpissa',
  'admin.audienceId': 'Yleisön tunniste',
  'admin.audienceHint': 'Kenelle luonnokset osoitetaan. Vastaanottajat voi aina vaihtaa Mailchimpissa ennen lähetystä.',
  'admin.members.one': '1 tilaaja',
  'admin.members.other': '{n} tilaajaa',
  'admin.plan': 'Mailchimp-paketti',
  'admin.plan.standard': 'Standard tai Premium',
  'admin.plan.essentials': 'Essentials',
  'admin.plan.unknown': 'En tiedä',
  'admin.planHint': 'Essentials-paketissa Mailchimp ei lähetä muualla tehtyä kirjettä, joten dashboard tarjoaa silloin ensin kopiointia omaan pohjaanne.',
  'admin.fromName': 'Lähettäjän nimi',
  'admin.replyTo': 'Lähettäjän sähköpostiosoite',
  'admin.replyToHint': 'Tyhjänä käytetään yleisön omaa oletusta Mailchimpissa.',
  'admin.saved': 'Asetukset tallennettu.',
  'admin.howTitle': 'Miten Mailchimp yhdistetään',
  'admin.how1': 'Mailchimpissa: profiilikuva → Profile → Extras → API keys → Create A Key. Tee avain mieluiten käyttäjälle, jolla ei ole lähetysoikeutta.',
  'admin.how2': 'n8n:ssä: Credentials → DFP Mailchimp → liitä avain ja tallenna. Avain ei koskaan kulje dashboardin kautta.',
  'admin.how3': 'Kirjoita tähän datakeskus (avaimen loppuosa, esimerkiksi us4) ja tallenna.',
  'admin.how4': 'Paina "Testaa yhteys" ja valitse yleisö.',
  'admin.howSafety': 'Dashboard ei koskaan lähetä uutiskirjettä. Se tekee Mailchimpiin luonnoksia ja testiviestejä; lähetys tehdään aina Mailchimpissa.',

  'error.no_such_template': 'Tallennettua pohjaa tai osiota ei löydy.',
  'error.design_too_big': 'Sisältö on liian suuri tallennettavaksi.',
  'error.no_such_comment': 'Kommenttia ei löydy.',
  'error.not_your_comment': 'Vain kommentin kirjoittaja voi poistaa sen.',
  'error.no_such_image': 'Kuvaa ei löydy.',
  'error.image_in_use': 'Kuvaa käytetään uutiskirjeessä ({names}), joten sitä ei poisteta.',
  'error.no_image': 'Valitse ladattava kuva.',
  'error.not_a_video': 'Käytä YouTube- tai Vimeo-osoitetta.',
  'error.video_not_found': 'Videota ei löytynyt. Tarkista osoite.',
  'error.video_unreachable': 'Videopalveluun ei saatu yhteyttä. Yritä hetken päästä uudelleen.',
  'error.bad_email': 'Tarkista sähköpostiosoitteet.',
  'error.mailchimp_not_set_up': 'Mailchimp-yhteys ei ole käytössä: INGEST_TOKEN puuttuu .env-tiedostosta.',
  'error.mailchimp_no_server': 'Mailchimpin datakeskus puuttuu asetuksista.',
  'error.mailchimp_no_workflow': 'n8n:ssä ei ole Mailchimp-työnkulkua päällä.',
  'error.mailchimp_n8n_error': 'n8n vastasi virheellä ({status}).',
  'error.mailchimp_key': 'Mailchimp ei hyväksynyt avainta. Tarkista avain n8n:n DFP Mailchimp -tunnuksesta.',
  'error.mailchimp_forbidden': 'Mailchimp ei salli tätä tällä avaimella tai paketilla.',
  'error.mailchimp_not_draft': 'Mailchimpin kampanja on jo lähetetty tai ajastettu, joten sitä ei voi enää päivittää.',
  'error.mailchimp_audience': 'Mailchimpista ei löydy asetuksissa valittua yleisöä.',
  'error.mailchimp_choose_audience': 'Mailchimp-tilillä on useampi yleisö. Valitse asetuksista, mihin luonnokset tehdään.',
  'error.mailchimp_no_audience': 'Mailchimp-tilillä ei ole vielä yleisöä. Luo se ensin Mailchimpissa.',
  'error.mailchimp_not_connected': 'Mailchimpia ei ole yhdistetty.',
  'error.mailchimp_failed': 'Mailchimp ei suorittanut pyyntöä. {detail}',
  'error.mailchimp_missing': 'Mailchimpista ei löytynyt pyydettyä kohdetta. Se on ehkä poistettu.',
  'error.mailchimp_busy': 'Mailchimp pyytää odottamaan hetken. Yritä uudelleen minuutin päästä.',
  'error.mailchimp_bad_request': 'Pyyntö Mailchimpiin oli puutteellinen. Tarkista datakeskus asetuksista.',
};

export const en = {
  'nav.newsletters': 'Newsletters',
  'nav.settings': 'Settings',

  'list.title': 'Newsletters',
  'list.lead': 'Every newsletter, drafts first. They are made here and sent from Mailchimp.',
  'list.create': 'Create newsletter',
  'list.createTitle': 'Create a newsletter',
  'list.createButton': 'Create and open the editor',
  'list.nameLabel': 'Name',
  'list.nameHint': 'Only you see the name. Leave it empty and it is named after the month. New picks go into this newsletter.',
  'list.search': 'Search by name or subject',
  'list.filter': 'Show',
  'list.filter.all': 'All',
  'list.filter.draft': 'Drafts',
  'list.filter.sent': 'Sent',
  'list.col.name': 'Name',
  'list.col.edited': 'Edited',
  'list.col.status': 'Status',
  'list.col.mailchimp': 'Mailchimp',
  'list.col.actions': 'Actions',
  'list.status.draft': 'Draft',
  'list.status.sent': 'Sent',
  'list.subject': 'Subject: {subject}',
  'list.noSubject': 'No subject line',
  'list.articles.one': '1 article',
  'list.articles.other': '{n} articles',
  'list.comments.one': '1 open comment',
  'list.comments.other': '{n} open comments',
  'list.current': 'New picks go here',
  'list.edit': 'Edit',
  'list.open': 'Open',
  'list.editContent': 'Edit content',
  'list.preview': 'Preview',
  'list.rename': 'Rename',
  'list.replicate': 'Use as template',
  'list.replicateTitle': 'A new newsletter from this one',
  'list.replicateHint': 'The new newsletter gets the same look and texts, with the newly picked articles. Leave the name empty and it is named after the month.',
  'list.delete': 'Delete',
  'list.deleteConfirm': 'Delete the draft {name}? Its {n} picked articles go back to the Articles page, undecided.',
  'list.deleted': 'Deleted: {name}',
  'list.more': 'More actions: {name}',
  'list.nothing': 'Nothing found.',
  'list.emptyTitle': 'No newsletters yet',
  'list.emptyLead': 'A newsletter starts by itself when you pick the first article on the Articles page. You can also create one here.',
  'list.manyDrafts': 'There is more than one draft. Articles picked on the Articles page go into the newest, marked "New picks go here".',
  'list.mcNone': 'Not exported',
  'list.mcDraft': 'Draft in Mailchimp, exported {when}',
  'list.mcScheduled': 'Scheduled in Mailchimp',
  'list.mcSent': 'Sent from Mailchimp',
  'list.mcMarked': 'Marked as sent',
  'list.mcDeleted': 'Deleted from Mailchimp',

  'issue.toList': 'Newsletters',
  'issue.back': 'Back',
  'issue.finishLater': 'Finish later',
  'issue.export': 'Export to Mailchimp',
  'issue.rename': 'Rename',
  'issue.progress': '{done}/{total} done',
  'issue.sentNote': 'Sent {date}. It can no longer be changed, but it can be the template for a new one.',
  'issue.lineArticles': 'Articles',
  'issue.lineSubject': 'Subject',
  'issue.lineContent': 'Content',
  'issue.lineMailchimp': 'Mailchimp',
  'issue.articleCount.one': '1 article picked',
  'issue.articleCount.other': '{n} articles picked',
  'issue.noArticles': 'No articles picked yet. Pick them on the Articles page.',
  'issue.pickMore': 'Pick articles',
  'issue.show': 'Show',
  'issue.hide': 'Hide',
  'issue.unpickConfirm': 'Remove the article from this newsletter? It goes back to the Articles page, undecided.',
  'issue.subjectQuestion': "What's the subject line?",
  'issue.addSubject': 'Add a subject line',
  'issue.edit': 'Edit',
  'issue.preheaderShown': 'Preview text: {text}',
  'issue.noPreheader': 'No preview text.',
  'issue.design': 'Design the email',
  'issue.notDesigned': 'Not opened in the editor yet. The editor builds it from the picked articles.',
  'issue.editContent': 'Edit content',
  'issue.mailchimpHow': 'When the content is ready, export it to Mailchimp. Recipients are chosen there and the email is sent from there.',
  'issue.recipients': '{n} recipients',
  'issue.openPreview': 'Open in a new tab',

  'handoff.title': 'Export to Mailchimp',
  'handoff.lead': 'The email goes into Mailchimp, and you send it from there. Choose a way; we recommend the top one.',
  'handoff.recommended': 'Recommended',
  'handoff.plan.standard': 'Mailchimp plan: Standard or Premium.',
  'handoff.plan.essentials': 'Mailchimp plan: Essentials.',
  'handoff.plan.unknown': 'The Mailchimp plan is not set in Settings. On Essentials, only copying works.',
  'handoff.draftTitle': 'A draft straight into Mailchimp',
  'handoff.draftLead': 'One click and the email, its images, subject line and preview text are in Mailchimp as a ready draft.',
  'handoff.essentialsWarning': 'On the Essentials plan Mailchimp will not send an email made elsewhere; it asks for an upgrade to Standard. Copy into your own template instead.',
  'handoff.connectedTo': 'Connected to the Mailchimp account {name}.',
  'handoff.notConnected': 'Mailchimp is not connected. An admin connects it on the Settings page.',
  'handoff.draftStep1': 'Press "Create draft in Mailchimp".',
  'handoff.draftStep2': "Open the draft in Mailchimp. It is in the Campaigns list under this newsletter's name.",
  'handoff.draftStep3': 'In Mailchimp, choose the recipients, send yourself a test, then send or schedule it.',
  'handoff.createDraft': 'Create draft in Mailchimp',
  'handoff.updateDraft': 'Update the draft in Mailchimp',
  'handoff.updateConfirm': "Updating replaces the Mailchimp draft's content with this newsletter's. Changes made to the content in Mailchimp are lost. Go ahead?",
  'handoff.exporting': 'Exporting…',
  'handoff.exported': 'Exported to Mailchimp {when} ({name}).',
  'handoff.exportedToast': 'The draft is in Mailchimp now.',
  'handoff.changedSince': 'Changed since it was exported. Update the draft in Mailchimp.',
  'handoff.openInMailchimp': 'Open in Mailchimp',
  'handoff.copyTitle': 'Copy into your own Mailchimp template',
  'handoff.copyLead': "Works on every Mailchimp plan. The email is put together in Mailchimp's own editor from your usual template.",
  'handoff.copyStep1': 'In Mailchimp, start a new email from your usual template, or replicate the last newsletter (Campaigns → ▾ → Replicate).',
  'handoff.copyStep2': 'Press "Copy" by a section, click a text block in Mailchimp and paste (Cmd+V, Ctrl+V on Windows).',
  'handoff.copyStep3': "Finally copy the subject line and preview text into Mailchimp's Subject.",
  'handoff.picturesCopied': 'Images are copied into Mailchimp when you copy a section, so readers see them.',
  'handoff.picturesLocal': 'The dashboard is not on the internet yet, so images will not show in Mailchimp. Add the images in Mailchimp, or connect Mailchimp so they are copied there.',
  'handoff.copy': 'Copy',
  'handoff.copied': 'Copied',
  'handoff.copiedSection': 'Copied: {name}. Paste it into Mailchimp.',
  'handoff.copiedThing': 'Copied: {what}',
  'handoff.copyFailed': "Couldn't copy in this browser.",
  'handoff.subject': 'subject line',
  'handoff.preheader': 'preview text',
  'handoff.copySubject': 'Copy subject line',
  'handoff.copyPreheader': 'Copy preview text',
  'handoff.codeTitle': "Alternative: the whole email at once into Mailchimp's Code block",
  'handoff.codeLead': "Mailchimp's own editor has a Code block that takes a whole email. Add a Code block to an empty email and paste this into it. Test first whether your plan allows it.",
  'handoff.copyCode': 'Copy the whole email as code',
  'handoff.wholeEmail': 'the whole email',
  'handoff.fileTitle': 'As a file',
  'handoff.fileLead': 'Download the email as a file and import it into Mailchimp as a template. The images travel inside the file.',
  'handoff.fileStep1': 'Download the ZIP file.',
  'handoff.fileStep2': 'In Mailchimp: Campaigns → Email templates → Code your own ▾ → Import ZIP, and choose the file.',
  'handoff.fileStep3': 'Save the template (Save and Exit).',
  'handoff.fileStep4': 'Create an email from it: Saved tab → the template → Create email. Choose the recipients and send.',
  'handoff.downloadZip': 'Download ZIP',
  'handoff.downloadHtml': 'Download HTML',
  'handoff.copyHtml': 'Copy HTML',
  'handoff.zipTooBig': 'The file is {kb} KB. Mailchimp takes files under 1 MB: shrink or remove images.',
  'handoff.afterSending': 'Did you send it from Mailchimp some other way than as the draft? Mark it sent so its articles show as used.',

  'admin.title': 'Settings',
  'admin.lead': 'The Mailchimp connection, and how drafts are made in Mailchimp.',
  'admin.mailchimp': 'Mailchimp',
  'admin.test': 'Test the connection',
  'admin.testing': 'Testing…',
  'admin.testOk': 'The connection works.',
  'admin.testBad': 'The connection does not work. The reason is on the page.',
  'admin.connected': 'Connected to the Mailchimp account {name}.',
  'admin.audienceLine': 'Audience: {name}, {n} subscribers',
  'admin.notConnectedTitle': 'Not connected.',
  'admin.notConnected': "n8n couldn't reach Mailchimp.",
  'admin.server': 'Mailchimp data centre',
  'admin.serverHint': "It is in Mailchimp's address when you are logged in: us4.admin.mailchimp.com → us4. It is also the end of the API key.",
  'admin.audience': 'Audience',
  'admin.audienceNone': 'Chosen in Mailchimp',
  'admin.audienceId': 'Audience id',
  'admin.audienceHint': 'Who drafts are addressed to. The recipients can always be changed in Mailchimp before sending.',
  'admin.members.one': '1 subscriber',
  'admin.members.other': '{n} subscribers',
  'admin.plan': 'Mailchimp plan',
  'admin.plan.standard': 'Standard or Premium',
  'admin.plan.essentials': 'Essentials',
  'admin.plan.unknown': "Don't know",
  'admin.planHint': 'On Essentials Mailchimp will not send an email made elsewhere, so the dashboard then offers copying into your own template first.',
  'admin.fromName': "Sender's name",
  'admin.replyTo': "Sender's email address",
  'admin.replyToHint': "Empty uses the audience's own default in Mailchimp.",
  'admin.saved': 'Settings saved.',
  'admin.howTitle': 'How to connect Mailchimp',
  'admin.how1': 'In Mailchimp: profile picture → Profile → Extras → API keys → Create A Key. Preferably for a user who cannot send.',
  'admin.how2': 'In n8n: Credentials → DFP Mailchimp → paste the key and save. The key never passes through the dashboard.',
  'admin.how3': 'Type the data centre here (the end of the key, such as us4) and save.',
  'admin.how4': 'Press "Test the connection" and choose the audience.',
  'admin.howSafety': 'The dashboard never sends the newsletter. It makes drafts and test emails in Mailchimp; sending always happens in Mailchimp.',

  'error.no_such_template': 'That saved template or section was not found.',
  'error.design_too_big': 'The content is too big to save.',
  'error.no_such_comment': 'That comment was not found.',
  'error.not_your_comment': 'Only whoever wrote a comment can delete it.',
  'error.no_such_image': 'That image was not found.',
  'error.image_in_use': 'The image is used in a newsletter ({names}), so it stays.',
  'error.no_image': 'Choose an image to upload.',
  'error.not_a_video': 'Use a YouTube or Vimeo address.',
  'error.video_not_found': 'The video was not found. Check the address.',
  'error.video_unreachable': "Couldn't reach the video service. Try again in a moment.",
  'error.bad_email': 'Check the email addresses.',
  'error.mailchimp_not_set_up': 'The Mailchimp connection is off: INGEST_TOKEN is missing from .env.',
  'error.mailchimp_no_server': 'The Mailchimp data centre is missing from Settings.',
  'error.mailchimp_no_workflow': 'n8n has no Mailchimp workflow switched on.',
  'error.mailchimp_n8n_error': 'n8n answered with an error ({status}).',
  'error.mailchimp_key': "Mailchimp didn't accept the key. Check the key in n8n's DFP Mailchimp credential.",
  'error.mailchimp_forbidden': "Mailchimp doesn't allow this with this key or plan.",
  'error.mailchimp_not_draft': 'The Mailchimp campaign has been sent or scheduled, so it can no longer be updated.',
  'error.mailchimp_audience': "The audience chosen in Settings isn't in Mailchimp.",
  'error.mailchimp_choose_audience': 'The Mailchimp account has more than one audience. Choose the one for the drafts in Settings.',
  'error.mailchimp_no_audience': 'The Mailchimp account has no audience yet. Create one in Mailchimp first.',
  'error.mailchimp_not_connected': 'Mailchimp is not connected.',
  'error.mailchimp_failed': "Mailchimp didn't do it. {detail}",
  'error.mailchimp_missing': "Mailchimp doesn't have what was asked for. It may have been deleted.",
  'error.mailchimp_busy': 'Mailchimp asks to wait a moment. Try again in a minute.',
  'error.mailchimp_bad_request': 'The request to Mailchimp was incomplete. Check the data centre in Settings.',
};
