// The words of Asetukset → Lähteet: every source and how it is doing,
// adding one, the sites worth adding, and the card on Asetukset that leads
// there. texts.js adds them to the dashboard's own.
// Jira: DM42-29, DM42-80

export const fi = {
  'src.title': 'Lähteet',
  'src.back': 'Asetukset',
  'src.lead': 'Mistä artikkelit tulevat: syötteet, lehdet, arkistot ja seuratut sivut. Lähteet tarkistetaan joka päivä klo {times}.',
  'src.leadOff': 'Mistä artikkelit tulevat: syötteet, lehdet, arkistot ja seuratut sivut. Automaattiset tarkistukset ovat pois päältä.',
  'src.add': 'Lisää lähde',
  'src.tabs': 'Näytä',
  'src.tab.on': 'Käytössä',
  'src.tab.attention': 'Huomioitavaa',
  'src.tab.off': 'Pois päältä',
  'src.tab.all': 'Kaikki',
  'src.search': 'Hae nimellä tai osoitteella',
  'src.none': 'Hakuun sopivia lähteitä ei ole.',
  'src.noneTab': 'Tässä ei ole lähteitä.',
  'src.list': 'Lähteet',
  'src.new30.one': '1 uusi 30 päivässä',
  'src.new30.other': '{n} uutta 30 päivässä',
  'src.weeks': 'Uudet jutut viikoittain, 12 viikkoa, uusin oikealla',

  'src.kind.rss': 'Syöte',
  'src.kind.crossref': 'Lehti, Crossref',
  'src.kind.dspace': 'Arkisto',
  'src.kind.webpage': 'Sivusto',
  'src.kind.watch': 'Seurattu sivu',
  'src.kind.drive': 'Drive-kansio',
  'src.kind.manual': 'Telegram-botti',

  'src.health.ok': 'Toimii',
  'src.health.failed': 'Haku epäonnistui',
  'src.health.quiet': 'Hiljainen',
  'src.health.waiting': 'Ei vielä tarkistettu',
  'src.health.checking': 'Tarkistetaan…',
  'src.health.unread': 'Ei lukijaa',
  'src.health.off': 'Pois päältä',

  'src.why.ok': 'Tarkistettu {when}: {found} juttua, joista {new} uutta.',
  'src.why.drive': 'Drive-kansio luetaan 15 minuutin välein. Asetusten kohta Google Drive kertoo enemmän.',
  'src.why.manual': 'Linkit, jotka tiimi lähettää Telegram-botille. Botti on aina päällä.',
  'src.why.failed': 'Viimeisin haku {when} epäonnistui: {error}',
  'src.why.failedMoved': 'Syötettä ei löydy enää tästä osoitteesta. Etsi sen uusi osoite kohdasta Vaihda osoite.',
  'src.why.failedOnce': 'Usein tilapäinen: seuraava tarkistus yrittää uudelleen.',
  'src.why.quiet': 'Ei uusia juttuja {days} päivään.',
  'src.why.quietNever': 'Ei yhtään juttua sen jälkeen, kun sitä alettiin tarkistaa.',
  'src.why.waiting': 'Tarkistetaan ensimmäisen kerran {when}.',
  'src.why.waitingNoTime': 'Tarkistetaan, kun sitä pyydetään: automaattiset tarkistukset ovat pois päältä.',
  'src.why.checking': 'Tarkistus on käynnissä.',
  'src.why.unread': 'Sivustolla ei ole syötettä, eikä mikään lue sitä. Anna sille syöte tai seurattava sivu kohdasta Vaihda osoite.',
  'src.why.off': 'Pois päältä. Sen jutut pysyvät tallessa.',

  'src.pick': 'Valitse lähde',
  'src.pickHint': 'Näet, miten se toimii, mitä se on tuonut ja mitä siitä tuodaan.',
  'src.homepage': 'Sivusto',
  'src.counts.new': 'uutta 30 päivässä',
  'src.counts.picked': 'valittu uutiskirjeisiin',
  'src.counts.total': 'kaikkiaan',
  'src.latest': 'Uusimmat jutut',
  'src.latestNone': 'Ei vielä yhtään juttua.',
  'src.allArticles': 'Kaikki lähteen jutut Artikkeleissa',
  'src.runs': 'Tarkistukset',
  'src.run': '{found} löytyi, {new} uutta',
  'src.runRunning': 'käynnissä',
  'src.runsNone': 'Ei vielä tarkistettu.',
  'src.settings': 'Lähteen asetukset',
  'src.name': 'Nimi',
  'src.publisher': 'Julkaisija',
  'src.publisherHint': 'Näkyy uutiskirjeessä jutun yhteydessä, kun juttu ei itse kerro tekijäänsä.',
  'src.language': 'Kieli',
  'src.languageUnknown': 'Ei tiedossa',
  'src.filter': 'Mitä tuodaan',
  'src.filter.always': 'Kaikki jutut',
  'src.filter.keywords': 'Vain avainsanoilla',
  'src.filter.on_request': 'Vain pyydettäessä',
  'src.filterMeans.always': 'Jokainen juttu tiivistetään.',
  'src.filterMeans.keywords': 'Juttu tiivistetään, kun siinä on jokin suodattimen avainsanoista, kuten oppi, opetus tai tekoäly. Muut ohitetaan.',
  'src.filterMeans.on_request': 'Jutut tallennetaan, ja ne tiivistetään vasta, kun joku pyytää tai seurattu aihe tuo ne Uusiin.',
  'src.filterFixed': 'Tästä lähteestä tuodaan jutut sen omalla tavalla.',
  'src.section': 'Ehdotettava osio',
  'src.sectionNone': 'Ei omaa osiota',
  'src.sectionHint': 'Tapahtuma, jolla on päivä, ja jäsenten kuulumiset menevät aina omiin osioihinsa. Tämä koskee lähteen muita juttuja.',
  'src.pictures': 'Kuvat',
  'src.notes': 'Muistiinpano',
  'src.notesHint': 'Esimerkiksi miksi lähde on pois päältä.',
  'src.save': 'Tallenna',
  'src.saving': 'Tallennetaan…',
  'src.saved': 'Lähde ”{name}” tallennettu.',
  'src.picturesConfirm': 'Lähteen ”{name}” kuvia ei enää haeta, ja sen käyttämättömät kuvat poistetaan. Jatketaanko?',
  'src.switch': 'Käytössä',
  'src.switchLabel': 'Lähde ”{name}” käytössä',
  'src.switchedOn': 'Lähde ”{name}” on taas käytössä.',
  'src.switchedOff': 'Lähde ”{name}” on pois päältä. Sen jutut pysyvät.',
  'src.check': 'Tarkista nyt',
  'src.checkStarted': 'Lähdettä ”{name}” tarkistetaan. Tulos näkyy tässä minuutin sisällä.',
  'src.changeAddress': 'Vaihda osoite',
  'src.delete': 'Poista lähde',
  'src.deleteConfirm': 'Poistetaanko lähde ”{name}”? Siitä ei ole tullut yhtään juttua.',
  'src.deleted': 'Lähde ”{name}” poistettu.',
  'src.cannotDelete.one': 'Lähteellä on yksi juttu, joten sen voi vain laittaa pois päältä. Silloin juttu pysyy ja tietää, mistä se tuli.',
  'src.cannotDelete.other': 'Lähteellä on {n} juttua, joten sen voi vain laittaa pois päältä. Silloin jutut pysyvät ja tietävät, mistä ne tulivat.',
  'src.special.drive': 'Drive-kansio otetaan käyttöön ja pois Asetusten kohdassa Google Drive.',
  'src.special.manual': 'Botti on aina päällä. Linkit lähetetään sille Telegramissa.',
  'src.openDrive': 'Avaa Google Driven asetukset',
  'src.addedBy': 'Lisännyt {name}, {when}.',
  'src.changedBy': 'Viimeksi muuttanut {name}, {when}.',
  'src.onSite': 'Samalta sivustolta luetaan myös: {names}.',

  'src.sugg.title': 'Ehdotuksia',
  'src.sugg.lead': 'Sivustot, joille aiemmat uutiskirjeet linkittivät, ja jäsenorganisaatioiden sivustot. Mikään lähde ei vielä lue niitä.',
  'src.sugg.links.one': '{links} linkkiä yhdessä uutiskirjeessä',
  'src.sugg.links.other': '{links} linkkiä {n} uutiskirjeessä',
  'src.sugg.member': 'Jäsenorganisaatio: {name}',
  'src.sugg.result.feed': 'Syöte löytyi',
  'src.sugg.perMonth': 'noin {n} juttua kuussa',
  'src.sugg.result.page': 'Ei syötettä, sivua voi seurata',
  'src.sugg.result.none': 'Ei syötettä eikä seurattavaa sivua',
  'src.sugg.result.blocked': 'Ei salli automaattista lukemista',
  'src.sugg.result.failed': 'Sivustoa ei saatu luettua',
  'src.sugg.result.unknown': 'Tarkistetaan…',
  'src.sugg.add': 'Lisää',
  'src.sugg.addLabel': 'Lisää {host} lähteeksi',
  'src.sugg.dismiss': 'Ei kiinnosta',
  'src.sugg.dismissLabel': 'Ei kiinnosta: {host}',
  'src.sugg.dismissed': '{host} piilotettu ehdotuksista.',
  'src.sugg.restore': 'Palauta',
  'src.sugg.restoreLabel': 'Palauta ehdotuksiin: {host}',
  'src.sugg.more': 'Näytä kaikki ({n})',
  'src.sugg.less': 'Näytä vähemmän',
  'src.sugg.hidden': 'Piilotetut ({n})',
  'src.sugg.looking': 'Sivustoja tarkistetaan. Tulokset tulevat tähän sitä mukaa.',
  'src.sugg.lookAgain': 'Tarkista uudelleen',
  'src.sugg.none': 'Ei ehdotuksia: jokainen sivusto, jolle aiemmat uutiskirjeet linkittivät useammin kuin kerran, on jo lähteenä.',

  'src.addTitle': 'Lisää lähde',
  'src.changeTitle': 'Vaihda osoite: {name}',
  'src.addLabel': 'Osoite',
  'src.addPlaceholder': 'kansanvalistusseura.fi tai ISSN 2227-7102',
  'src.addHint': 'Sivuston, syötteen tai uutissivun osoite, tai lehden ISSN. Työkalu etsii syötteen itse.',
  'src.find': 'Etsi',
  'src.finding': 'Etsitään…',
  'src.found.feed': 'Syöte löytyi',
  'src.found.journal': 'Lehti löytyi Crossrefistä',
  'src.found.page.one': 'Syötettä ei ole, mutta sivulla on yksi juttu, jota voi seurata',
  'src.found.page.other': 'Syötettä ei ole, mutta sivulla on {n} juttua, joita voi seurata',
  'src.found.via': 'Löytyi sivulta {page}.',
  'src.found.none': 'Täältä ei löytynyt syötettä eikä juttuja seurattavaksi.',
  'src.found.blocked': 'Sivusto ei salli automaattista lukemista. Sitä ei lisätä, kuten yhdistyksen kanssa on sovittu.',
  'src.found.listings': 'Kokeile näitä sivuja:',
  'src.found.latest': 'Uusimmat',
  'src.found.watchNote': 'Työkalu katsoo sivun joka tarkistuksessa ja tuo sen uudet linkit juttuina.',
  'src.found.fullText': 'Juttujen koko teksti luetaan, koska sivusto sallii sen.',
  'src.found.feedText': 'Vain syötteen oma teksti luetaan.',
  'src.found.journalText': 'Lehdestä luetaan vain otsikko ja tiivistelmä, ei koskaan koko artikkelia.',
  'src.found.exists': 'Tätä osoitetta luetaan jo: {name}.',
  'src.found.existsOff': 'Tätä osoitetta luetaan jo, mutta lähde on pois päältä: {name}.',
  'src.found.open': 'Avaa lähde',
  'src.import.one': 'Tuo myös sivulla nyt oleva juttu',
  'src.import.other': 'Tuo myös sivulla nyt olevat {n} juttua',
  'src.importHint': 'Muuten tulevat vain tästä eteenpäin julkaistut.',
  'src.addNow': 'Lisää lähde',
  'src.adding': 'Lisätään…',
  'src.added': 'Lähde ”{name}” lisätty. Se tarkistetaan {when}.',
  'src.addedNow': 'Lähde ”{name}” lisätty. Tarkista se nyt, niin jutut tulevat heti.',
  'src.useAddress': 'Käytä tätä osoitetta',
  'src.changed': 'Lähteen ”{name}” osoite vaihdettu.',

  'src.card.lead': 'Lisää, vaihda ja laita pois päältä lähteitä, katso miten kukin toimii, ja valitse lähteen kuvat ja ehdotettava osio.',
  'src.card.counts': '{on} käytössä, {off} pois päältä.',
  'src.card.failed.one': 'Yhden lähteen viimeisin haku epäonnistui: {names}.',
  'src.card.failed.other': '{n} lähteen viimeisin haku epäonnistui: {names}.',
  'src.card.quiet.one': 'Yksi lähde on hiljainen: {names}.',
  'src.card.quiet.other': '{n} lähdettä on hiljaisia: {names}.',
  'src.card.unread.one': 'Yhtä käytössä olevaa lähdettä ei lue mikään: {names}.',
  'src.card.unread.other': '{n} käytössä olevaa lähdettä ei lue mikään: {names}.',
  'src.card.ok': 'Jokaisen käytössä olevan lähteen viimeisin haku onnistui.',
  'src.card.open': 'Avaa lähteet',
  'src.card.andMore': '{names} ja {n} muuta',

  'error.source_exists': 'Tätä osoitetta luetaan jo.',
  'error.source_private_address': 'Oman verkon osoitteita ei lueta.',
  'error.source_bad_address': 'Tämä ei ole verkko-osoite.',
  'error.source_unreachable': 'Sivustoa ei tavoitettu. Tarkista osoite.',
  'error.source_not_found': 'Osoitteessa ei ole mitään (404).',
  'error.source_refused': 'Sivusto ei salli automaattista lukemista.',
  'error.source_http_error': 'Sivusto vastasi virheellä.',
  'error.source_too_many_redirects': 'Osoite ohjaa eteenpäin liian monta kertaa.',
  'error.source_special': 'Tätä lähdettä muutetaan siellä, missä se on otettu käyttöön.',
  'error.source_has_articles': 'Lähteellä on juttuja, joten sen voi vain laittaa pois päältä.',
  'error.source_not_checked': 'Vain käytössä olevan lähteen, jonka aikataulu lukee, voi tarkistaa.',
};

export const en = {
  'src.title': 'Sources',
  'src.back': 'Settings',
  'src.lead': 'Where the articles come from: feeds, journals, archives and watched pages. The sources are checked every day at {times}.',
  'src.leadOff': 'Where the articles come from: feeds, journals, archives and watched pages. Automatic checks are off.',
  'src.add': 'Add a source',
  'src.tabs': 'Show',
  'src.tab.on': 'On',
  'src.tab.attention': 'Needs a look',
  'src.tab.off': 'Off',
  'src.tab.all': 'All',
  'src.search': 'Search by name or address',
  'src.none': 'No source matches.',
  'src.noneTab': 'No sources here.',
  'src.list': 'Sources',
  'src.new30.one': '1 new in 30 days',
  'src.new30.other': '{n} new in 30 days',
  'src.weeks': 'New articles a week, 12 weeks, the newest on the right',

  'src.kind.rss': 'Feed',
  'src.kind.crossref': 'Journal, Crossref',
  'src.kind.dspace': 'Archive',
  'src.kind.webpage': 'Website',
  'src.kind.watch': 'Watched page',
  'src.kind.drive': 'Drive folder',
  'src.kind.manual': 'Telegram bot',

  'src.health.ok': 'Working',
  'src.health.failed': 'Check failed',
  'src.health.quiet': 'Quiet',
  'src.health.waiting': 'Not checked yet',
  'src.health.checking': 'Checking…',
  'src.health.unread': 'Nothing reads it',
  'src.health.off': 'Off',

  'src.why.ok': 'Checked {when}: {found} articles, {new} of them new.',
  'src.why.drive': 'The Drive folder is read every 15 minutes. Settings, under Google Drive, says more.',
  'src.why.manual': 'The links the team sends to the Telegram bot. The bot is always on.',
  'src.why.failed': 'The last check, {when}, failed: {error}',
  'src.why.failedMoved': 'The feed is no longer at this address. Find its new one under Change the address.',
  'src.why.failedOnce': 'Often temporary: the next check tries again.',
  'src.why.quiet': 'No new articles for {days} days.',
  'src.why.quietNever': 'Not one article since it began to be checked.',
  'src.why.waiting': 'Checked for the first time {when}.',
  'src.why.waitingNoTime': 'Checked when asked: automatic checks are off.',
  'src.why.checking': 'Being checked now.',
  'src.why.unread': 'The site has no feed, and nothing reads it. Give it a feed or a page to watch under Change the address.',
  'src.why.off': 'Switched off. Its articles stay.',

  'src.pick': 'Pick a source',
  'src.pickHint': 'You see how it is doing, what it has brought, and what comes in from it.',
  'src.homepage': 'Site',
  'src.counts.new': 'new in 30 days',
  'src.counts.picked': 'picked for newsletters',
  'src.counts.total': 'in all',
  'src.latest': 'Newest articles',
  'src.latestNone': 'No articles yet.',
  'src.allArticles': 'All its articles in Articles',
  'src.runs': 'Checks',
  'src.run': '{found} found, {new} new',
  'src.runRunning': 'running',
  'src.runsNone': 'Not checked yet.',
  'src.settings': 'The source’s settings',
  'src.name': 'Name',
  'src.publisher': 'Publisher',
  'src.publisherHint': 'Printed with an article in the newsletter when the article does not say who wrote it.',
  'src.language': 'Language',
  'src.languageUnknown': 'Not known',
  'src.filter': 'What comes in',
  'src.filter.always': 'Every article',
  'src.filter.keywords': 'Only with the keywords',
  'src.filter.on_request': 'Only on request',
  'src.filterMeans.always': 'Every article is summarised.',
  'src.filterMeans.keywords': 'An article is summarised when it has one of the filter’s keywords, such as learning, teaching or AI. The rest are skipped.',
  'src.filterMeans.on_request': 'Articles are kept, and summarised only when someone asks or a followed topic brings them to New.',
  'src.filterFixed': 'This source brings its articles in its own way.',
  'src.section': 'Section to suggest',
  'src.sectionNone': 'No section of its own',
  'src.sectionHint': 'An event with a date and the members’ news always go to their own sections. This decides the rest of its articles.',
  'src.pictures': 'Pictures',
  'src.notes': 'Note',
  'src.notesHint': 'For example why the source is switched off.',
  'src.save': 'Save',
  'src.saving': 'Saving…',
  'src.saved': 'Source “{name}” saved.',
  'src.picturesConfirm': 'Pictures from “{name}” are no longer fetched, and its unused pictures are deleted. Go ahead?',
  'src.switch': 'On',
  'src.switchLabel': 'Source “{name}” on',
  'src.switchedOn': 'Source “{name}” is on again.',
  'src.switchedOff': 'Source “{name}” is off. Its articles stay.',
  'src.check': 'Check now',
  'src.checkStarted': 'Checking “{name}”. The result shows here within a minute.',
  'src.changeAddress': 'Change the address',
  'src.delete': 'Delete the source',
  'src.deleteConfirm': 'Delete the source “{name}”? It has not brought a single article.',
  'src.deleted': 'Source “{name}” deleted.',
  'src.cannotDelete.one': 'It has one article, so it can only be switched off. Then the article stays and keeps where it came from.',
  'src.cannotDelete.other': 'It has {n} articles, so it can only be switched off. Then they stay and keep where they came from.',
  'src.special.drive': 'The Drive folder is switched on and off in Settings, under Google Drive.',
  'src.special.manual': 'The bot is always on. Links are sent to it on Telegram.',
  'src.openDrive': 'Open the Google Drive settings',
  'src.addedBy': 'Added by {name}, {when}.',
  'src.changedBy': 'Last changed by {name}, {when}.',
  'src.onSite': 'Also read from the same site: {names}.',

  'src.sugg.title': 'Worth adding',
  'src.sugg.lead': 'Sites the past newsletters linked to, and the member organisations’ sites. No source reads them yet.',
  'src.sugg.links.one': '{links} links in one newsletter',
  'src.sugg.links.other': '{links} links in {n} newsletters',
  'src.sugg.member': 'Member organisation: {name}',
  'src.sugg.result.feed': 'Has a feed',
  'src.sugg.perMonth': 'about {n} articles a month',
  'src.sugg.result.page': 'No feed; a page can be watched',
  'src.sugg.result.none': 'No feed and no page to watch',
  'src.sugg.result.blocked': 'Refuses to be read automatically',
  'src.sugg.result.failed': 'The site could not be read',
  'src.sugg.result.unknown': 'Being looked at…',
  'src.sugg.add': 'Add',
  'src.sugg.addLabel': 'Add {host} as a source',
  'src.sugg.dismiss': 'Not interested',
  'src.sugg.dismissLabel': 'Not interested: {host}',
  'src.sugg.dismissed': '{host} hidden from the suggestions.',
  'src.sugg.restore': 'Bring back',
  'src.sugg.restoreLabel': 'Bring back to the suggestions: {host}',
  'src.sugg.more': 'Show all ({n})',
  'src.sugg.less': 'Show fewer',
  'src.sugg.hidden': 'Hidden ({n})',
  'src.sugg.looking': 'The sites are being looked at. The results come in here as they do.',
  'src.sugg.lookAgain': 'Look again',
  'src.sugg.none': 'Nothing to suggest: every site the past newsletters linked to more than once is a source already.',

  'src.addTitle': 'Add a source',
  'src.changeTitle': 'Change the address: {name}',
  'src.addLabel': 'Address',
  'src.addPlaceholder': 'kansanvalistusseura.fi or ISSN 2227-7102',
  'src.addHint': 'A site’s, a feed’s or a news page’s address, or a journal’s ISSN. The tool finds the feed itself.',
  'src.find': 'Find',
  'src.finding': 'Looking…',
  'src.found.feed': 'A feed was found',
  'src.found.journal': 'Found in Crossref',
  'src.found.page.one': 'No feed, but the page has one article that can be watched',
  'src.found.page.other': 'No feed, but the page has {n} articles that can be watched',
  'src.found.via': 'Found from the page {page}.',
  'src.found.none': 'No feed and no articles to watch were found here.',
  'src.found.blocked': 'The site refuses to be read automatically. It is not added, as agreed with the association.',
  'src.found.listings': 'Try these pages:',
  'src.found.latest': 'Newest',
  'src.found.watchNote': 'The tool looks at the page at every check and brings its new links in as articles.',
  'src.found.fullText': 'The articles are read in full, as the site allows it.',
  'src.found.feedText': 'Only the feed’s own text is read.',
  'src.found.journalText': 'Only the title and abstract are read, never the whole article.',
  'src.found.exists': 'This address is read already: {name}.',
  'src.found.existsOff': 'This address is read already, but the source is off: {name}.',
  'src.found.open': 'Open the source',
  'src.import.one': 'Bring in the article on the page now too',
  'src.import.other': 'Bring in the {n} articles on the page now too',
  'src.importHint': 'Otherwise only those published from now on come in.',
  'src.addNow': 'Add the source',
  'src.adding': 'Adding…',
  'src.added': 'Source “{name}” added. It is checked {when}.',
  'src.addedNow': 'Source “{name}” added. Check it now to bring its articles in at once.',
  'src.useAddress': 'Use this address',
  'src.changed': 'The address of “{name}” changed.',

  'src.card.lead': 'Add, change and switch off sources, see how each is doing, and choose a source’s pictures and the section to suggest.',
  'src.card.counts': '{on} on, {off} off.',
  'src.card.failed.one': 'The last check of one source failed: {names}.',
  'src.card.failed.other': 'The last check of {n} sources failed: {names}.',
  'src.card.quiet.one': 'One source is quiet: {names}.',
  'src.card.quiet.other': '{n} sources are quiet: {names}.',
  'src.card.unread.one': 'Nothing reads one source that is on: {names}.',
  'src.card.unread.other': 'Nothing reads {n} sources that are on: {names}.',
  'src.card.ok': 'The last check of every source that is on went well.',
  'src.card.open': 'Open the sources',
  'src.card.andMore': '{names} and {n} more',

  'error.source_exists': 'This address is read already.',
  'error.source_private_address': 'Addresses inside our own network are not followed.',
  'error.source_bad_address': 'That is not a web address.',
  'error.source_unreachable': 'The site could not be reached. Check the address.',
  'error.source_not_found': 'There is nothing at that address (404).',
  'error.source_refused': 'The site refuses to be read automatically.',
  'error.source_http_error': 'The site answered with an error.',
  'error.source_too_many_redirects': 'The address sends us on too many times.',
  'error.source_special': 'This source is changed where it is set up.',
  'error.source_has_articles': 'The source has articles, so it can only be switched off.',
  'error.source_not_checked': 'Only a source that is on and read by the schedule can be checked.',
};
